### ISSUE TITLE
Can not find controllers in Steam VR

### ISSUE THREAD

**Issue by winiaa11090** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#10]
I set the file and when i start beatsaber, my controller is on the ground and in steam vr, 
![image](https://user-images.githubusercontent.com/44671258/61923888-8e632080-afa0-11e9-9f18-c323404147c4.png) like this
and more it sounds with noise can you help me?

**Comment by realistic40** [comment]
New Oculus firmware update broke most sideloaded apps, which relive appears to be one of. Will need to wait for an update from the developer to resolve or you can try the steps in the link below, though they didn't work for me.

https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/

**Comment by realistic40** [comment]
Updating the code and signing it gets the controllers back, but the left controller freezes up every few seconds and the sound doesn't work.

**Comment by GennadiyAMD** [comment]
@realistic40 , @winiaa11090 - version 1.0.14 addresses the issue with controllers. Running this APK on devices that have not received a firmware update to v7.00 from Oculus will trigger it - you might see a message box saying "Update in Progress, please leave the device on, with WiFi and power connected" upon running the updated app. The update takes a long time (several hours), so I'd suggest to leave the headset on overnight. Once the update is done, please reboot the headset.

@realistic40 - many thanks for the pointer about the manifest change! I was able to reproduce the controllers on the floor and left controller freezing every couple of seconds, but didn't see any issues with sound. Please let me know if you're still experiencing the sound issues after the update.

**Comment by winiaa11090** [comment]
@GennadiyAMD
thank you sir! Then, do i have to downgrademy quest?

**Comment by GennadiyAMD** [comment]
@winiaa11090  - no need to downgrade anything. You should be good. Please let me know how the latest build works out for you.

**Comment by winiaa11090** [comment]
@GennadiyAMD Okay! i was installed it, and tested
some bugs i found
 1.sound was shocking. it sounded only Ultra bass
2. graphics is too crumble to play well  
my setting is 

{
	"Application" : 
	{
		"AdjustChaperone" : true,
		"EnableManagementServer" : false,
		"HeadsetProfile" : "Oculus Rift CV1",
		"ManagementServerPort" : 8080,
		"PairedHeadsetsOnly" : false,
		"PairingModeEnabled" : false,
		"UseControllers" : true
	},
	"Audio" : 
	{
		"In_Channels" : 2,
		"In_SampleFormat" : "S16",
		"In_SampleRate" : 44100,
		"Out_AudioBitrate" : 128000,
		"Out_TimeShift" : 0
	},
	"Common" : 
	{
		"SettingsVersion" : 8
	},
	"Controller" : 
	{
		"DOF" : 6,
		"Description" : ""
	},
	"Display" : 
	{
		"DOF" : 6,
		"DumpPath" : "",
		"EnableDump" : false,
		"EncoderResolution" : 
		{
			"height" : 0,
			"width" : 0
		},
		"EyeResolution" : 
		{
			"height" : 1600,
			"width" : 1440
		},
		"FOV" : 
		{
			"height" : 1.7453292608261108,
			"width" : 1.7453292608261108
		},
		"IPD" : 0.0640000030398369,
		"MaxFrameRate" : 10000.0000000000000000,
		"MinFrameRate" : 40.0000000000000000,
		"VideoBitrate" : 100000000,
		"VideoCodec" : "default"
	},
	"Headset" : 
	{
		"DatagramSize" : 65507,
		"LogPath" : "",
		"Network" : "UDP",
		"Port" : 1235,
		"VirtualWallSize" : 
		{
			"height" : 0.0000000000000000,
			"width" : 0.0000000000000000
		},
		"VirtualWallType" : "None"
	}
}

or is that has mistake?
more, i want to opinion to you. 
in android apps, Relive streaming has a function that display(monitor) off when streming. 
it helps graphics card consume less resources
i wish it'll be in the option of relive vr. 
Thanks for your patch

**Comment by winiaa11090** [comment]
and more, VR CHAT can't congize mic and only left controller vibrate for example, in beat saber, I cut the block with my right controller, but left controller vibrate

**Comment by MikhailAMD** [comment]
@winiaa11090  what is your graphic card?
In any case it is better to keep square resolution: 1440,1440.
Also please try lower bit rate:50000000

**Comment by GennadiyAMD** [comment]
@winiaa11090 - EyeResolution.height of 1600 is too high - reset it back to 1440. I'd also leave the bitrate at 50000000, which is the default. You will hardly see any difference in image quality, but 100Mbps might be pushing the limits of your network. Leave everything at defaults - the only thing you need to change is HeadsetProfile.

I'm not sure I understand what you said about audio. We do not do any enhancements to the sound - just capture, encode, transmit, decide and play. Could it be that you have some enhancements enabled in Windows audio settings?

Microphone is not supported at the moment.

I'll check the haptics, thanks for reporting it.

**Comment by winiaa11090** [comment]
@MikhailAMD i using rx590 8gb model thanks for your advise

@GennadiyAMD okay i will do it thanks for your advise, and i will record it and send you

**Comment by winiaa11090** [comment]
@GennadiyAMD  here, thanks https://struc.kr/sharing/XH7kNRiik

**Comment by winiaa11090** [comment]
@GennadiyAMD Hey! i have a good news! after installing windows new update, this phenomenon was dissappointed! now, my problem is graphics and haptics

graphics:The letters look dim.
haptics: only right vibrates

Thank you.

**Comment by realistic40** [comment]
@GennadiyAMD No problem, glad I could help! To add to the thread, I'm not having any issues with sound.

**Comment by GennadiyAMD** [comment]
@winiaa11090 - fixed the haptics, but the fix is on the PC side, so it should become available when the next driver update comes out. 

Just to confirm I understand you correctly, when you said the letter looked 'dim', did you mean 'blurry' or 'fuzzy'?

**Comment by winiaa11090** [comment]
@GennadiyAMD I can cognize with look shape and think 
But font is really fuzzy 
I want a picture quality like ALVR

**Comment by GennadiyAMD** [comment]
@winiaa11090 - there's always a trade-off between the resolution and the frame rate. You can limit the max frame rate by setting the Display.MaxFrameRate to some value below 72 (like 60 or 65) and increase EncoderResolution. This will make the image sharper, but you'd loose the frame rate and would also have an increase in latency, which might be significant. 

RX5700 could go higher resolution and maintain the fps, but with RX590 you're pretty much at the limit of what the card can do.

**Comment by winiaa11090** [comment]
@GennadiyAMD 
The rx590 used by others was quite pleasant. I've used VD before and changed it. Can this make a problem?
https://www.youtube.com/watch?v=gtODDHB8eIc&lc=z22vsdgpyqeyel33eacdp4345w1b4ncphzg2dv0nzehw03c010c.1563807634407858

**Comment by GennadiyAMD** [comment]
@winiaa11090 - what are the titles where you see the text fuzziness?

**Comment by winiaa11090** [comment]
@GennadiyAMD Everything in steamVr,any games everything!

**Comment by GennadiyAMD** [comment]
@winiaa11090 - you can try reducing your field of view in settings.json by setting _Display.FOV.width_ and _Display.FOV..height_ down to 1.57079632679. The price you will pay is more artifacts at the edges when you move your head. You can play with these values to find the ones that you like the most.

**Comment by winiaa11090** [comment]
@GennadiyAMD can you say me what is my quest's problem?
is it ethernet? or computer hardware?

in the Virture Desktop, the display's quality is pretty good. but in RELIVE VR, probably not
