### ISSUE TITLE
Feature request:Please add Oculus Quest 2 controller support

### ISSUE THREAD

**Issue by Stoptimerag** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#100]
In Steam VR Home,Quest2 controller is not working good,some function is strange.But in game,its good,such as Alyx.

**Comment by GennadiyAMD** [comment]
@Stoptimerag - could you please be more specific? What exactly is strange?

**Comment by Stoptimerag** [comment]
> @Stoptimerag - could you please be more specific? What exactly is strange?

my setting is wrong
