### ISSUE TITLE
Sideloading Games not working

### ISSUE THREAD

**Issue by InfoSecIdiot** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#106]
Hey guys, 
Any ideas for this? I have downloaded two separate games using ITCH but there are certain (more than most of the ones I've tried) that give me a local certificate error. Now, I'm now tech wizard like you all but I feel like an idiot because I have tried on VPN, off VPN, looked in unknown sources, looked in Oculus TV, tried install to headset and looking for developers direct website - nothing is working for me and I'm getting pissed I am the only one missing out on all of these cool titles developed.

**Comment by InfoSecIdiot** [comment]
![Uploading image.png…]()

**Comment by GennadiyAMD** [comment]
@InfoSecIdiot - what does all this have to do with AMD ReLive VR? ReLive VR is a solution for streaming SteamVR games from a PC to your headset. If you sideloaded these games to your headset, then you should play them **outside** ReLive VR. If you loaded them to the PC then look for them somewhere in your Steam library or just launch the game and if it works through OpenVR, it would launch SteamVR automatically.

To sideload apps to Quest you need to register for an Oculus developer account and link it to an "organization". You can do all this through [Oculus Developer Dashboard](https://dashboard.oculus.com/), but again, this has absolutely nothing to do with ReLive VR.

Sounds like you're posting to a wrong forum?

**Comment by InfoSecIdiot** [comment]
Thanks bud. Seems that I am....I just really need help sideloading games
because it's like nothing works and there's soooo many titles to enjoy.
