### ISSUE TITLE
ReLive VR supporting 120Hz? 

### ISSUE THREAD

**Issue by r4instrm** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#107]
Hi. Recently I've updated my Quest 2 to V28 and enabled 120 Hz feature. Much to my surprise, after launching ReLive on headset and SteamVR on PC, SteamVR pop-up reported that I'm running on 120Hz. Even fpsVR shows 120 fps in games. 120 Hz streaming seems like a great feature but I'm not sure if it's real - ReLive VR hasn't got an update for few months. Is it possible that ReLive supports now 120 Hz without needing an update? 

![120Hz](https://user-images.githubusercontent.com/83775068/117346368-f2ba5000-aea7-11eb-9989-a61709ac0843.png)

**Comment by GennadiyAMD** [comment]
@r4instrm - it is real :) We read the supported fps from the headset, so if the headset reports that it's capable of 120Hz, then ReLive VR would see that. There would be no need to update it for that. As long as your GPU is capable of doing 120Hz, I see no reason for it not to work.

But your screenshot shows 40Hz, not 120?

**Comment by r4instrm** [comment]
Sorry, took screenshot when headset wasn't on my head ;) I'm so excited that 120 Hz is working properly. I hope my RX 6800 won't have trouble running some games in 120 fps. Great work guys! 

![120Hz](https://user-images.githubusercontent.com/83775068/117346595-3ca33600-aea8-11eb-89c7-ac94a70b0e73.png)

**Comment by GennadiyAMD** [comment]
@r4instrm - Thank you! 

Whether RX6800 is fast enough depends on the game - one could always create content that could tax any, even the most powerful GPU to the point that it wouldn't be able to keep up. But the important thing is that the encoder in RX6800 is fast enough to run at 120Hz.
