### ISSUE TITLE
Recording the output to hdd at the same time

### ISSUE THREAD

**Issue by patientx** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#111]
So... is that possible ? To record whatever we are sending from pc to quest ? Before sending it quest maybe or at the same time ?

**Comment by GennadiyAMD** [comment]
@patientx - theoretically yes, but practically, not really. Not reliably, at least. Spinning drives typically cannot sustain this kind of throughput  - their performance varies greatly depending on where on the platter the file is located - speeds on the inner cylinders are much lower than on the outer (as much as x3 lower). Write speeds on SSDs are also greatly affected by caches and often cannot be sustained for a very long time. And if the drive cannot keep up, then you would either block on sending to the headset, or have an uncontrolled memory growth. Remember that we're dealing with **sustained** 25-50Mbps for one eye only, with occasional spikes that could easily double that and no buffering on transmission.
