### ISSUE TITLE
Audio not streaming to headset.

### ISSUE THREAD

**Issue by alazyhitman** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#12]
For some reason the audio only plays from my computer and not from my Quest at all. Can't figure out how to fix this.

**Comment by GennadiyAMD** [comment]
@alazyhitman - some games require the input focus to be on them - they stop playing sound when they loose focus. Also what playback devices do you see when you right-click on the speaker in the bottom-right corner of the Windows bar and then select "Playback devices" from the menu? Which devices are there, what is the default and where are the speakers that work connected?

**Comment by GennadiyAMD** [comment]
@alazyhitman - do you have ALVR or Vridge on the same system by any chance? If you do, try removing them from the external_drivers array in %LOCALAPPDATA%\openvr\openvrpaths.vrpath, then restart SteamVR. I was just able to reproduce the no sound issue when I had both ReLive VR and ALVR registered at the same time. When you have multiple drivers loaded, the first one to start might get a hold of audio capture in an exclusive mode and block it off for the other. Please let me know if this resolves the issue for you. Thanks!

**Comment by alazyhitman** [comment]
Ok so I removed the ALVR from the openvrpaths as mentioned above and started getting static through the Quest now. I can hear faint sound from Steam and games but it's mostly static.

**Comment by alazyhitman** [comment]
Finally got it working! Followed the steps above and then had to select "Steam Streaming Speakers" as my device. Thank you!!!!

**Comment by MikhailAMD** [comment]
Static meaning silence, corruption low volume?
What is your computer output: stereo or some multichannel?

**Comment by alazyhitman** [comment]
The static is resolved now, I just had to select the right audio output device on my computer.

**Comment by MikhailAMD** [comment]
Oh, good still, what was your original configuration?

**Comment by alazyhitman** [comment]
I had my wireless headset selected as the output device originally. I didn't think I'd have to select any particular device for it to play from my Quest but I guess I was wrong.
