### ISSUE TITLE
Headset stuck standing by

### ISSUE THREAD

**Issue by xdevilkillx** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#123]
The headset icon stays grey, no controller icons, and headset never shows Steam Dashboard to do first time setup.

**Comment by GennadiyAMD** [comment]
@xdevilkillx - check your Windows Firewall settings. A very common problem - your network connection is set to Public in Windows, but the firewall dialog that pops up the first time you run it has checkmarks for Private and Domain by default. If you just clicked OK, you did not open the firewall. Change network type to Private in Windows Settings.

Also check that your headset and the PC are on the same IP subnet.
