### ISSUE TITLE
quest controllers not working 

### ISSUE THREAD

**Issue by chanhoon** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#13]

**Comment by chanhoon** [comment]
i did setting all. but my computer doesn't recognize my controller. i changed vive to cv1. driver is latest version. what should i

**Comment by elmerohueso** [comment]
If you have Third Party Controller enabled in ReLive settings, you need to disable it.  Then your controllers will render in game as the CV1 controllers.
