### ISSUE TITLE
ReLive & VR Streaming settings missing on RX 550

### ISSUE THREAD

**Issue by SelynCatto** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#130]
**Setup**
 - OS: Windows 11
 - Headset: Quest 2
 - Driver Version: 22.3.1
 - ReLive version: Unknown
 - GPU: RX 550 4 GB
 
 Hi, I'm using Radeon Software Adrenalin but I don't seem to be able to find the wireless vr streaming settings in radeon software or anything mentioning it. I can't even find anything ReLive related anywhere?
 
 Please, how do I get the option?

**Comment by GennadiyAMD** [comment]
RX550 is not considered VR-capable. It might work, but performance would be quite poor.
Check if you have c:\Program Files\AMD\WVR folder. If you do, you can go inside the OpenVR folder and run the registerdriver.cmd script, which would register ReLive VR with Steam. After that you can just start SteamVR and it should work - you won't get the Settings page in Radeon Software, but you can enable the Web UI and use that instead.

**Comment by SelynCatto** [comment]
Hey uh, the wlvr folder is not there. But is there any possible way to download it from elsewhere to do it?
