### ISSUE TITLE
Streaming Tab is Empty in Radeon ReLive VR Settings Webpage

### ISSUE THREAD

**Issue by pendragonmikel** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#133]
I've been using ReLive for some time and had dialed in settings under the streaming tab previously. Now the page loads, the Status and Headset Tabs are fine, but the Streaming tab is empty. 

**To Reproduce**
1. Enable/Configure ReLive VR
2. Enable Management Server and make changes in page.
3. Use Service/Update Drivers as they come out. 
4. Load management page
5. Click on Streaming - page is blank.

**Setup (please complete the following information):**
 - OS: Windows 10
 - Headset Quest 2
 - Driver Version [e.g. 22.5.2]
 - ReLive version 2.0
 - GPU ASROCK TAICHI 6800XT

**Logs and Settings (please attach or share):**
{
	"Application" : 
	{
		"AdjustChaperone" : true,
		"EnableManagementServer" : true,
		"HeadsetProfile" : "Oculus Quest 2",
		"ManagementServerPort" : 8080,
		"PairedHeadsetsOnly" : true,
		"PairingModeEnabled" : false,
		"UseControllers" : true
	},
	"Audio" : 
	{
		"In_CaptureSource" : false,
		"In_ChannelLayout" : 0,
		"In_Channels" : 2,
		"In_SampleFormat" : "S16",
		"In_SampleRate" : 44100,
		"In_StreamSampleRate" : 0,
		"Out_AudioBitrate" : 128000,
		"Out_TimeShift" : 0
	},
	"Common" : 
	{
		"SettingsVersion" : 10
	},
	"Controller" : 
	{
		"DOF" : 6,
		"Description" : null
	},
	"Display" : 
	{
		"10BitSRGB" : false,
		"DOF" : 6,
		"DumpPath" : null,
		"EnableDump" : false,
		"EncoderResolution" : 
		{
			"height" : 1920,
			"width" : 1832
		},
		"EncoderStereo" : true,
		"EyeResolution" : 
		{
			"height" : 2448,
			"width" : 2448
		},
		"FOV" : 
		{
			"height" : 1.7453292608261108,
			"width" : 1.7453292608261108
		},
		"IPD" : 0.0640000030398369,
		"KeepAspectRatio" : false,
		"MaxFrameRate" : 80.0000000000000000,
		"MinFrameRate" : 72.0000000000000000,
		"NonLinearScale" : true,
		"VideoBitrate" : 170000000,
		"VideoCodec" : "hevc",
		"VideoEnableHDR" : false,
		"VideoSliceCount" : 1,
		"VideoSliceOutput" : false
	},
	"Headset" : 
	{
		"BindInterface" : "*",
		"DatagramSize" : 65507,
		"EnableNetwork" : true,
		"LogPath" : "C:\Program Files (x86)\Steam\logs\",
		"MaxUserCount" : 1,
		"Microphone" : true,
		"Network" : "UDP",
		"Port" : 1235,
		"UserConnectionTimeout" : 30,
		"VerifyFirewall" : true
	}
}

**Expected behavior**
Streaming tab should contain all configurations as it did previously. 

**Screenshots**
![image](https://user-images.githubusercontent.com/102331382/174171071-8e0f157e-29d5-4ab9-a369-bc6a2f75b465.png)

**Additional context**
Worked fine before, not sure if a driver update broke it at some point. Using ReLive VR thankfully still works. 
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/8922631/AMDWirelessVR.log)

**Comment by GennadiyAMD** [comment]
@pendragonmikel - thanks for pointing it out. Yes, a regression has slipped into this release - we also caught it, but a bit too late, unfortunately. It's already fixed in one of the up-coming releases. You can still edit the settings.json file manually if you need to change anything - it's located in %LOCALAPPDATA%\AMD\OpenVR\settings.

**Comment by pendragonmikel** [comment]
Glad to know there's a fix coming soon. Thanks and keep up the good work.


-------- Original message --------
From: Gennadiy_AMD ***@***.***>
Date: 6/16/22 7:19 PM (GMT-05:00)
To: GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR ***@***.***>
Cc: pendragonmikel ***@***.***>, Mention ***@***.***>
Subject: Re: [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR] Streaming Tab is Empty in Radeon ReLive VR Settings Webpage (Issue #133)


@pendragonmikel<https://github.com/pendragonmikel> - thanks for pointing it out. Yes, a regression has slipped into this release - we also caught it, but a bit too late, unfortunately. It's already fixed in one of the up-coming releases. You can still edit the settings.json file manually if you need to change anything - it's located in %LOCALAPPDATA%\AMD\OpenVR\settings.

**Comment by pendragonmikel** [comment]
Do we know which driver version this will be fixed in? I was really hoping it would have been in 22.6.1, but it wasn't. It would be great if the next driver release would fix both this issue and the Oculus bitrate issue.

**Comment by pendragonmikel** [comment]
Fixed with driver version 22.7.1.
