### ISSUE TITLE
SteamVR/ReliveVR do not detect HMD (Meta Quest 2)

### ISSUE THREAD

**Issue by KiraiNah** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#141]
**Description:**
I have all the software installed correctly, but when I start the app on my headset and open SteamVR, the only thing I can see is a Wi-Fi icon in a green box on the bottom left, which turns gray over time.
![image](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/assets/148493355/b892fd9c-217e-4fed-8834-9238210c54a5)
![image](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/assets/148493355/d1c94bc8-bcda-4653-bb06-2f4031ae676e)

On the headsets, I see a white place, and a headset icon with a Wi-Fi symbol above it.

I understand that this happened to many people, and I saw that few managed to solve it.

**Setup:**
 - OS: Windows 10
 - Headset: Meta Quest 2
 - Driver Version: 23.9.2
 - ReLive version: I don't know, but I think it's de "2.0" version.
 - GPU: RX 570

**Logs and Settings:**
- AMDWirelessVR.log: 
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/13047152/AMDWirelessVR.log)

- settings.json:
I couldn't find this file.

**Comment by GennadiyAMD** [comment]
@KiraiNah - most likely you have a firewall issue as there are no signs of the PC receiving any requests from the headset. Have you tried everything suggested in this [Wiki chapter](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Network-Setup)?

A few things to check:
1. Headset and the PC are on the same IP subnet (assuming your network mask is 255.255.255.0, the first three numbers of the IP address of the PC and the headset would be the same). This might not be the case if your network topology includes more than one router or WiFi access point. Some routers assign different subnets to wired and wireless - rare, but we've seen those, for example, HTC 5G modems
2. Make sure your network type in Windows is **not** set to Public, or that you've allowed vrserver.exe through Windows Firewall for Public networks as well (the Public checkbox in the firewall popup dialog is off by default).

settings.json is located in %LOCALAPPDATA%\AMD\OpenVR\settings. %LOCALAPPDATA% is a hidden directory under c:\Users\<your user name>\AppData\Local - you would need to enable showing hidden files in Windows Explorer to see it (View->check Hidden items)

Hope this helps.

**Comment by KiraiNah** [comment]
Hello again. I was corroborating what you said, but in the process I realized that my Oculus were connected to a different Wi-Fi network than my computer, but coming from the same router (5g).
By changing it I was able to connect to my PC with ReliveVR from my headsets, allowing me to see the SteamVR home, which did not last long because moments later the image distorted and froze.
I found no alternative but to close ReliveVR.

Do you know any solution for this new problem?
I say new because I don't know how related it is to the previous one.

Attached "settings.json":
[settings.json](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/13058576/settings.json)

**Comment by GennadiyAMD** [comment]
Now that you can connect, please send the new AMDWirelessVR.log.

 One things that comes to mind - try reducing the bitrate (VideoBitrate parameter in settings.json) to 100000000 (100Mb) or lower. It is currently set to 170MBps, not all routers are capable of this kind of bandwidth, also depends on what's between you and the router (steel studs in the walls, metal vents, etc), distance, interference, etc.

Also you said that your headset was connected to a different WiFi network than your computer. Is your computer connected wirelessly as well? If so, connect it to the router with a cable. Wireless is semi-duplex, so having two wireless links in the path could definitely be detrimental.

**Comment by KiraiNah** [comment]
Hello again. I was corroborating what you said, but in the process I realized that my Oculus were connected to a different Wi-Fi network than my computer, but coming from the same router (5g).
By changing it I was able to connect to my PC with ReliveVR from my headsets, allowing me to see the SteamVR home, which did not last long because moments later the image distorted and froze.
I found no alternative but to close ReliveVR.

Do you know any solution for this new problem?
I say new because I don't know how related it is to the previous one.

Attached "settings.json":
[settings.json](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/13058752/settings.json)

**Comment by GennadiyAMD** [comment]
See my previous message

**Comment by KiraiNah** [comment]
Hello again. I was corroborating what you said, but in the process I realized that my Oculus were connected to a different Wi-Fi network than my computer, but coming from the same router (5g).
By changing it I was able to connect to my PC with ReliveVR from my headsets, allowing me to see the SteamVR home, which did not last long because moments later the image distorted and froze.
I found no alternative but to close ReliveVR.

Do you know any solution for this new problem?
I say new because I don't know how related it is to the previous one.

Attached "settings.json":

**Comment by KiraiNah** [comment]
I'm sorry, I just send the message twice.

Continuing with this, I lowered the bitrate where you told me, I tried to connect the hedsets with the PC and the image froze again and the following happened:

![safdasfdasfds](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/assets/148493355/7e447e03-a4e2-410a-907c-f611443bd9ef)


Restarted the computer, made a second attempt and more of the same:

![SAFASFS2](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/assets/148493355/96069911-ceee-43ca-b598-088b5506341f)


Clarifying about the Wi-Fi, in fact, I am 1 room away from the router and I am not on Ethernet, but it works flawlessly with AirLink (Aside from the recurring crashes due to incompatibility in the drivers that many people have).

Attachment "AMDWirelessVR.log":
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/13059390/AMDWirelessVR.log)

**Comment by GennadiyAMD** [comment]
@KiraiNah - the RX570 generation had a slower AVC encoder and the log clearly shows encoder queue overflow. Switch to HEVC. You can do this by changing the VideoCodec parameter in settings.json to "hevc". You should also be able to do this through Radeon Software or through the [Web interface](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Configuration-Using-a-Web-Browser).

I'd also suggest to enable NonLinearScale (set to true), if you keep experiencing issues, you might want to try to lower resolution to something like 1200x1200.

RX470 is a really old GPU. I think it came out back in 2015 or so, so you might want to consider upgrading it.

**Comment by KiraiNah** [comment]
Good news!
I got an ethernet cable and it started working more or less fine.
I made some of the modifications you said and it works pretty well now.
I'm going to play with those values to optimize it as much as possible.

I am very grateful.

The only thing that happens to me is that, after playing for a while, the sound breaks.
Maybe I should try it in other games apart from the one I tried it on (Blade and Sorcery) just to confirm that it is not a problem with it.

But that, if you don't know the solution to this new problem, no problem, I feel like I have already taken up a lot of your time, so, it's ok.

**Comment by GennadiyAMD** [comment]
Always happy to help!

For sound, try setting the sampling rate in Windows to 16-bit, 44100Hz (right-click on the speaker on Windows toolbar->Sound Control Panel->Advanced tab)

**Comment by KiraiNah** [comment]
Great!
Well, I go were you say and tried to do that, but look:
![image](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/assets/148493355/9e59792c-a3ea-41bd-b16c-332a4e565614)

In my free time, I'll look for a video, web post or something where this problem is discussed. Maybe I'll find something there.

By the way, I don't know if this is your job or if you do it from the heart, but I saw that you are always attentive to people's questions and do everything with kindness.
It is admirable!
Your help is appreciated.

**Comment by GennadiyAMD** [comment]
Try changing the default audio output to speakers or headphones - we capture the sound from the default audio output. See if this would enable the greyed out combo box with audio parameters.

It is my job, among many other things :) Thanks for the kind words!

**Comment by KiraiNah** [comment]
I'm so sorry for the delay in answering.
So, I think the big problem has solve.
The audio didn't brakes again, but if that happen I will do what you say.

Anyway, thanks you so much again for your help.

I hope I don't have any more problems with this, so, in that case, I send you a big greeting.

Have a nice Halloween!
Good luck.

**Comment by GennadiyAMD** [comment]
@KiraiNah - always happy to help! 
Thanks a lot for your kind words!
