### ISSUE TITLE
No feedback right controller

### ISSUE THREAD

**Issue by elmerohueso** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#17]
Using Quest, only played Beat Saber.  All vibration feedback, even when it should go to the right controller, goes to the left controller.  Ie. move right pointer over a button, left controller vibrates.

**Comment by GennadiyAMD** [comment]
@elmerohueso - fixed in the upcoming Adrenalin driver

**Comment by GennadiyAMD** [comment]
@elmerohueso - please update your Radeon driver to 19.8.1 released yesterday.
