### ISSUE TITLE
Too dark scenes when playing Lone Echo / Echo Arena

### ISSUE THREAD

**Issue by romanpekarskiy** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#18]
I'm using Revive to play Lone Echo / Echo Arena on SteamVR, but game looks is too dark. When using Virtual Desktop everything is fine, exept poor latency. Looks like there are some issue with colorspaces.
Is there somekind of workaround to play Echo Arena streamed over AMD Relive VR? 
P.S. Guys, your work are awesome

**Comment by MikhailAMD** [comment]
We can expose a setting parameter adjusting gamma, but I am wandering if all games look dark or just this one.

**Comment by romanpekarskiy** [comment]
Noticed only in Echo Arena, Lone Echo and Lone Echo 2 Trailer.
I have asked at Revive community about that firstly, and we figured out it only reproduces on AMD ReLive VR, and for Virtual Desktop or ALVR picture looks normal. Guys from Relive tells me that caused because Echo Arena uses 10 bit sRGB, if that info could help

**Comment by MikhailAMD** [comment]
Could you please send a log file so we could check the format: 
C:\Program Files (x86)\Steam\logs\AMDWirelessVR.log.
Thanks,

**Comment by romanpekarskiy** [comment]
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/3493624/AMDWirelessVR.log)
hope it helps

**Comment by romanpekarskiy** [comment]
And in addition, how it looks and hot itsupposed to look:

![com amd wirelesshmd-20190811-172909](https://user-images.githubusercontent.com/13348334/62884944-5ac61b80-bd40-11e9-9b4d-415e54c45cc8.jpg)
![VirtualDesktop Android-20190811-171915](https://user-images.githubusercontent.com/13348334/62884949-5c8fdf00-bd40-11e9-99c6-42a6306b03cd.jpg)


![com amd wirelesshmd-20190811-173007](https://user-images.githubusercontent.com/13348334/62884956-60bbfc80-bd40-11e9-9550-3ebe3fd635c5.jpg)
![VirtualDesktop Android-20190811-171608](https://user-images.githubusercontent.com/13348334/62884959-6285c000-bd40-11e9-9d24-cbbf85e00cd2.jpg)

**Comment by MikhailAMD** [comment]
Thanks for the information. I think I know what happens: Oculus API has OVR_FORMAT_R11G11B10_FLOAT which in Revive is mapped to DXGI_FORMAT_R10G10B10A2_UNORM. The log you sent shows that ReLive VR is asked to create a swap chain with this DXGI format (24). Oculus format is SRGB. ReVive and ALVR interpret the corresponding DXGI format as SRGB while in DXGI spec this format is not SRGB. If a regular Vive application start using DXGI_FORMAT_R10G10B10A2_UNORM the DXGI-way - the colors will be wrong. So to get around this issue I am adding an option in ReLive VR settings file that will switch on/off the interpretation of 10-bit UNORM textures as SRGB. This feature will appear in the near hotfix driver release. When released, we will post a note with instructions how to use it.
Thanks again for the help.

**Comment by MikhailAMD** [comment]
This should be fixed in 19.8.2 driver release

**Comment by romanpekarskiy** [comment]
Yay! it works! i have found new setting `0BitSRGB`, it was `false` by default, setting it to `true` fixes dark scenes in Echo Arena. Didnt noticed how it impact other titles yet, but thank u guys, u are awesome!

**Comment by mutha64** [comment]
I've also got the same problem. I've got version 20.4.2 and I can't find the 10BitSRGB option.
Is there a file I can edit ?
Cheers

**Comment by GennadiyAMD** [comment]
@mutha64 - %LOCALAPPDATA%\AMD\OpenVR\settings\settings.json. All ReLive VR settings are saved there. It's a JSON file, so plain text, use your favorite text editor to edit. Just make sure that you save it as ASCII text and **not** Unicode.

**Comment by Kaborr** [comment]
I have an HP REVERB G2 for me it only worked:
AdvancedSettings-5.3.2-Installer

https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases/tag/v5.3.2

I selected Brightness and the game is running normally.
