### ISSUE TITLE
Oculus Quest controllers not providing input

### ISSUE THREAD

**Issue by Clavus** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#2]
I've installed the ReLiveVR APK on my Oculus Quest and enabled SteamVR Integration in Radeon Settings. The headset streaming worked right away, so that's great! The controllers were tracking, and recognised as Touch controllers (that's the model SteamVR assigned to them at least). However, they're not processing any button input. I can point at the menus in SteamVR Home but not select anything because of that.

Things I've tried:
- Enabled the Use Third-Party Controller option in Radeon Settings, but this just stopped the controllers from being enabled entirely.
- Modified the "Controller" section in the LocalAppData/AMD/OpenVR/settings/settings.json. I set the "Manufacturer" to "Oculus" and "Model" to "Touch". Didn't work, but I'm not sure what the expected values here should be.

I also noticed that the "Application" settings does not contain a "HeadsetProfile" as described in the Readme, but adding that does not change anything either.

**Comment by GennadiyAMD** [comment]
Please make sure you update the Adrenalin driver to the latest. We only added support for Touch controllers lately. Do a clean install.
What icons for headset and controllers do you see in SteamVR? The proper wireless and touch controllers or the hexagons with H and C in them? If you see hexagon, you're definitely running an older driver.
You can delete settings.json and it will get recreated next time you run SteamVR. Check if HeadsetProfile shows up then.

**Comment by Clavus** [comment]
I see the Hexagon icons. Will do the driver update later and report back.

**Comment by GennadiyAMD** [comment]
Definitely you have an old driver. When you install it, select the clean install option which uninstalls the current one first, just to be on the safe side.

**Comment by Clavus** [comment]
Updating the driver fixed it.
