### ISSUE TITLE
Does Relive support rift s emulation or simple cb1

### ISSUE THREAD

**Issue by BrotherO4** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#21]
simple question. 
if it does were can i go to find the list of device it can emu into? so i can keep my eye on it for the future or switch between said devices

**Comment by GennadiyAMD** [comment]
@BrotherO4 - currently ReLive VR emulates "HTC Vive", "HTC Vive Pro" and "Oculus Rift CV1". You can use these values in the settings.json file. Rift S emulation is coming at some point in the future, although the button mappings are exactly the same, it's really just the look of the controller. There's no list you can monitor, but once Rift S emulation is out, there will be a mention of it on the main page.
