### ISSUE TITLE
Oculus Revive Home Button

### ISSUE THREAD

**Issue by realistic40** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#22]
Is there a button combination that AMD ReLive provides that allows emulation of the Oculus Home button when using Oculus Revive? It's normally the left home button, but when used through SteamVR, this brings up the Steam menu instead. I saw posts from virtual desktop that they were looking into a button combination to emulate it so I figured I'd ask here to see if similar support is available.

**Comment by GennadiyAMD** [comment]
@realistic40 - we currently don't do anything special for Revive. And with the regular wired Rift in Steam the left home button brings up the Steam menu, just like we do with the Quest - did you actually mean the Oculus button on the **right** hand controller? That's what brings up the Oculus menu, isn't it? There's also the Revive button that gets integrated into the SteamVR system menu.

Any combination of buttons could potentially be used by some game for something else, if not now, it might be any time in the future, so we would be risking breaking compatibility with some titles.

**Comment by realistic40** [comment]
@GennadiyAMD Ah yes you are correct, left Oculus button isn't assigned and the Oculus menu is on the right hand controller. Could there potentially be a configurable option so that we can assign a button combo if we need it for certain Oculus Rift titles?

**Comment by realistic40** [comment]
You can disregard, I found that you can map inside SteamVR a double click of a button to the menu button.

**Comment by DicciusMaximus** [comment]
realistic how did you get revive to work
