### ISSUE TITLE
Issues with audio streaming on quest.

### ISSUE THREAD

**Issue by actualrednose** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#24]
I haven't been able to get the desktop audio to stream to the quest at all and I'm not sure why.

**Comment by GennadiyAMD** [comment]
@actualrednose - do you have ALVR or Riftcat installed on the same PC by any chance?

**Comment by trankuilized** [comment]
Same issues. Removed ALVR and updated drivers. In steamvr audio settings, it has 'do not change device' or 'remote'. Should it register the headset?

**Comment by GennadiyAMD** [comment]
@actualrednose , @trankuilized - could you please describe the symptoms in more detail? No sound at all ever or you get it at first and then it breaks off? I assume it's the former, but just making sure.
Could you also please attach the log file called AMDWirelessVR.log located in c:\Program Files (x86)\Steam\logs

Also more questions and suggestions:
- Do you have anything other than  the Quest connected to any of the audio outputs? Speakers, headphones, a monitor with built-in speakers? Please make sure you have at least one playback device connected
- Is your main sound output configured for 6 channels or Stereo? If it's 6 channels, try switching it to Stereo
- Leave all SteamVR audio settings at default ("do not change device")
- Make sure that the game's own window has input focus - some games stop audio playback when they loose focus

Thanks!

**Comment by actualrednose** [comment]
Managed to fix it by changing the output device in steamvr to steam streaming speakers and also deleting all of my ALVR files.

**Comment by trankuilized** [comment]
That's awesome @actualrednose and thanks @GennadiyAMD for the info. Per your suggestion of having at least one playback device connected,  I got it to work by leaving the tv or rdc on (don't have a monitor and speakers) but then it's sending to two displays which obviously causes issues. I don't have a pc speaker to connect but is that what I have to do to keep it working w/o sending to two displays? 

Thanks again for your help. Just got this headset and the vr community seems pretty great!
