### ISSUE TITLE
Hands are on the ground in Superhot VR

### ISSUE THREAD

**Issue by hauke725** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#27]
In the Steam Home everything works fine but in Superhot no interaction is possible due to the hands just laying on the ground and not moving

**Comment by hauke725** [comment]
[Some screenshots of what is going on](https://imgur.com/a/u7G0OiX)

**Comment by GennadiyAMD** [comment]
@hauke725 - thanks for catching this. We were able to reproduce the issue as well, will look into it. It seems to work fine when emulating HTC Vive, but not Oculus. Will need to dig into it, so we don't have a solution at the moment other than switching the heatset profile in settings.json to "HTC Vive" as a temporary workaround.
I will let you know once we have a solution.

**Comment by hauke725** [comment]
Thank you for the quick response! If the workaround does the trick that's good enough for me. I'm happy to see such fantastic support for this already amazing piece of software

**Comment by GennadiyAMD** [comment]
@hauke725 - this is definitely a game issue. If you join the Beta program on Steam, go to your Steam Library, right-click on Superhot, select the Properties option in the pop-up menu, go to the Betas tab and apply the 'old-steamvr-patch - Patch 1.0.8 with OpenVR...', controllers start working.

Source: [https://www.reddit.com/r/OculusQuest/comments/ci5vps/stream_superhot_steam_edition_to_my_quest_hands/](https://www.reddit.com/r/OculusQuest/comments/ci5vps/stream_superhot_steam_edition_to_my_quest_hands/)

[https://steamcommunity.com/app/382110/discussions/0/1639789306563336098/](https://steamcommunity.com/app/382110/discussions/0/1639789306563336098/)

It appears that the latest update of Superhot is attempting to access controllers directly through the Oculus API - with the real Rift CV1 I could start the game from SteamVR, then close SteamVR, but the game was still running in the headset with everything working. So it looks like they started prioritizing the native API over OpenVR.

**Comment by hauke725** [comment]
Thank you, I will try out the other version. Emulating the HTC Vive Controller did work, but the bindings are weird.
