### ISSUE TITLE
question,

### ISSUE THREAD

**Issue by BrotherO4** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#28]
i don't know where to ask said question so forgive.
Virtual Desktop added two big feature that vastly improve the streaming.
foveated encoding to improve the image quality in the center and  sliced encoding to reduce encoding/decoding latency. I dont know if its possible or if its even planned but..i hope these two feature some day makes it over to Relive Vr streaming.

**Comment by MikhailAMD** [comment]
We don't comment on upcoming features, though we are aware of these technologies. Thanks for the suggestion and pls stay tuned.

**Comment by BrotherO4** [comment]
alright, just that the last update was 2 months ago and i was worry that all development has stop lol

**Comment by BrotherO4** [comment]
i would also like to recommend another feature. 
Mic passthrough, 
that is all i pray for an update to be in the works

**Comment by GennadiyAMD** [comment]
@BrotherO4 - we're pleased to announce foveated scaling/encoding available with the Radeon Adrenalin 2020 Edition, along with a few other features like Rift S emulation, device pairing a more.
[Foveated Scaling](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Foveated-Scaling-in-ReLive-VR)
[Rift S emulation](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Controller-Emulation-in-ReLive-VR)
[Device pairing](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Network-Setup)

Thanks for using ReLive VR and AMD hardware!
