### ISSUE TITLE
Lone Echo: Menu buttons unresponsive with latest version of SteamVR (1.8.20)

### ISSUE THREAD

**Issue by eirinaios** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#29]
I accidentally updated SteamVR yesterday to version 1.8.20. Since then I am unable to play Lone Echo on my Oculus Quest. I inject it using Revive (any version), the game loads to the menu screen, my controllers appear connected and clearly are working as they should (I can use both my hands), but the game's menu buttons become unresponsive. Thus I cannot start the game...

This problem has been commented multiple times. The most successful workaround was to start steamVR, close Revive, reopen it and then inject the Lone Echo executable. Unfortunately it doesn't work. I tried older versions of SteamVR (unfortunately not 1.7.15 I was running until yesterday because I can't find it anywhere) and revive, but the result was the same. Finally, I reverted to the latest versions of SteamVR and Revive and tried to play the game using ALVR. To my surprise the controllers were functioning properly. The same stands for Virtual Desktop.

I would really appreciate if you could look into this issue as I find Relive by far the best SteamVR streaming solution to date.

**Comment by ClarkFamily** [comment]
I've had to a few custom keybindings when using Relive. ALVR and Virtual Desktop emulate different controllers I believe. Doesn't hurt to at least know how to do it.

**Comment by GennadiyAMD** [comment]
@ClarkFamily - ReLive VR also emulates HTC Vive/Vive Pro and Oculus Rift CV1 (Rift S emulation is coming soon). Given the overall number of questions we're getting we've decided to start a Wiki for ReLive VR, so the answer to your question is hopefully there: [https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Controller-Emulation-in-ReLive-VR](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Controller-Emulation-in-ReLive-VR). Please let us know if you require any additional information.

**Comment by MikhailAMD** [comment]
Please try the latest Adrenalin driver 20.1.1. We've fixed a similar issue.
https://www.amd.com/en/support
