### ISSUE TITLE
Oculus Quest controllers rotational tracking offset

### ISSUE THREAD

**Issue by Clavus** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#3]
I notice that the (CV1) Oculus Touch controllers rendered in SteamVR Home do not align nicely with my physical (Quest-style) Oculus Touch controllers. The rendered controllers appear to pitch down by about a 45 degree angle. Is this perhaps adjustable in the settings.json?

**Comment by GennadiyAMD** [comment]
Do controllers in SteamVR look like Oculus Touch or Vive? Do they have trackpads or joysticks?

**Comment by Clavus** [comment]
They are rendered as CV1 Touch controllers in SteamVR. I'll check if this issue persists after I do the Adrenalin driver update.

**Comment by Clavus** [comment]
Updating the driver did **not** fix this.

**Comment by tphamhuu** [comment]
Can confirm this issue.

**Comment by GennadiyAMD** [comment]
@Clavus, @tphamhuu - fixed in 1.0.11
Thanks for finding this!

**Comment by tphamhuu** [comment]
Thanks for fixing it! I am very grateful that you guys make it possible to sideload this app!
