### ISSUE TITLE
Asgard's Wrath "Game Paused"

### ISSUE THREAD

**Issue by gomork** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#31]
When starting Asgard's Wrath over ReLive and Revive, the Game starts up but immediatly stops on a "Game Paused" Screen, which cannot be overcome by button presses.
I tried uninstalling the ALVR-Driver, but that didn't change behavior.
Using ALVR it starts just fine.

**Comment by GennadiyAMD** [comment]
@gomork - could you please try switching the headset emulation to HTC Vive or Vive Pro as described [here](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Controller-Emulation-in-ReLive-VR) to see if it makes any difference? Thanks!

**Comment by gomork** [comment]
I just tried and it behaves exactly the same.

**Comment by andy-d1969** [comment]
Seems to be an issue with Revive and SteamVR 1.8. https://github.com/LibreVR/Revive/issues/1380

**Comment by MikhailAMD** [comment]
Please try the latest Adrenalin driver 20.1.1. We've fixed a similar issue.
https://www.amd.com/en/support
