### ISSUE TITLE
Tales of wedding rings vr stuck in PAUSE menu

### ISSUE THREAD

**Issue by orangpelupa** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#32]
As soon as you start the game, its stuck in the pause menu.

Maybe similar bug with asgard wrath? 

https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/issues/31

**Comment by MikhailAMD** [comment]
Please try the latest Adrenalin driver 20.1.1. We've fixed a similar issue.
https://www.amd.com/en/support
