### ISSUE TITLE
When i start the oculus quest client, SreamVR crashes.

### ISSUE THREAD

**Issue by sofaplayer2** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#33]
I have a vega 56 with the latest adrenalin drivers (19.12.3), ryzen 5 2600, windows 10 up to date, steamVR installed, and every time I open the sideloaded (1.0.19) app I get to see steamvr home for a second and it crashes. I only get to see the front, if i move my head it tracks it but all around is black, and after a few seconds I get the image of the goggles with the wireless symbol, like waiting to be connected.

In steamVR it says it's found a critical error, no error codes or anything.

I've tried ALVR and it works no problem. I uninstalled the ALVR drivers thinking that it was a driver issue (having 2 drivers at the same time) but no joy.

Any help will be greatly appreciated. Thanks in advance.

**Comment by sofaplayer2** [comment]
Hi, 
Yesterday I tested the oculus link with an amazon cable. It all worked as expected, and, to my surprise, after using the cable I tested amd relive vr with steamvr and worked.

I'll do some more testing today.

**Comment by sofaplayer2** [comment]
I think i found the issue. I had ALVR installed previously, and the openvr.vrpath file in users/appdata/local/openvr/ still had the path on it, but the driver had been uninstalled. once the path was deleted it started working.

hope it helps others with a similar issue.

**Comment by MikhailAMD** [comment]
thanks for letting us know.
