### ISSUE TITLE
Quest and PC won't pair

### ISSUE THREAD

**Issue by jonathanheron** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#34]
Hi,

After following the installation steps to install ReLive on my computer and Quest, I am unable to connect the quest to the computer -- instead when I run ReLive on the Quest, I see a VR icon with WiFi signals animated above it. A connection is never initiated.

Is there anything I can do to debug or fix this problem?

### Basics about my setup

- I'm running Adrenalin 2020 edition 19.12.3 with a Radeon Pro 575.
- The computer and Quest are on the same 5GHz WiFi network. 
- Quest is running version 1.0.20 of ReLiveVR-Oculus.
- Current version of Steam: built Dec 16 2019.
- Windows 10 Pro v 1903, build 18362.535.

In the AMD settings app:
- ReLive: on
- SteamVR Integration: enabled
- VR streaming protocol: UDP
- Accept connections from: any headsets

### What I observe

- SteamVR shows a headset active (with the green wifi-like symbol for ReliveVR)
- If I turn on Display VR View in SteamVR, I can see the computer is rendering the VR view.
- When I run ReLive on the Quest, I see a VR icon with WiFi signals animated above it. A connection is never initiated.
- In the AMD settings app, I see 0 paired headsets

### Some alternative configurations and steps I've tried, without luck

- I also tried Radeon Pro 19.12.3.
- I also tried running a hotspot from the computer, with the same results.
- I've verified SteamVR is permitted on my firewall.
- I've tried running with firewall disabled.
- I've verified my computer can ping the Quest.
- I've verified the Quest and computer are on the same subnet.
- I've tried choosing different emulated HMDs in ReLive.
- I've tried version 1.0.19 of ReLiveVR-Oculus.
- I've tried TCP streaming protocol.
- I've tried disabled allow connections from any headset; manually pairing doesn't result in any prompt appearing in the Quest.

**Comment by GennadiyAMD** [comment]
@jonathanheron

Hi Jonathan,

Could you please provide the following logs:

- c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log
- Open Windows command prompt and type: `ipconfig /all >c:\ipconfig.txt >%USERPROFILE%\ipconfig.txt` and attach this file (it will be in your user directory, if you type `echo %USERPROFILE%` on the command line, it would print the path to this directory)
- After you capture these logs, try disabling WiFi on your PC, make sure that the PC is connected to the router with an Ethernet cable, leaving just a single network adapter active in the system
- What is your router model?
- Any chance of trying to borrow a different router from a friend to see if this would make a difference?
- Do you have any non-default routing rules in your router? Anything that might possibly block UDP broadcasts? If you do, could you try disabling them/factory reset the router as the last resort?

**Comment by jonathanheron** [comment]
Thank you so much for following up. I'll try all this tomorrow and send over the logs etc.

**Comment by jonathanheron** [comment]
Ugh. I'm sorry to waste your time... but tinkering around to capture the info above somehow resulted in my setup working. I'm at a loss to explain why as I'm going through all the steps I went through last night.. Obviously I'm happy, but feel bad to have wasted your time. Unfortunately I didn't capture any logs from during a period the setup wasn't working, so I can't send you anything useful.
