### ISSUE TITLE
Pairing of HDM with ReLive Instance not possible with Radeon Pro?

### ISSUE THREAD

**Issue by duncanyb** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#35]
I tried to follow the described procedure to pair a headmounted display with a ReLive VR instance using the configuration screen, but it appears that the option isn't available in the Radeon Pro software today and only in Adrenalin 2020. (https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Network-Setup#pairing-a-headset-with-the-specific-pc)

Is there a plan to make this available for Radeon Pro in the future? I am testing VR workloads within a Virtual Machine and the aim is to have 6-8 VMs on the same hardware, in the same VLAN. Without the described functionality this becomes rather difficult.

Thanks,

Duncan Epping - VMware

**Comment by MikhailAMD** [comment]
Pro drivers are trailing behind with the latest features but eventually yes, it will be there. Please note that now  you can install non-Pro driver on Pro GPU. So you can try this feature right now. Search for Adrenaline Optional driver on the driver page for your GPU.

**Comment by duncanyb** [comment]
That is great to hear, thanks!

**Comment by GennadiyAMD** [comment]
@duncanyb - starting with the Adrenalin 2020 Edition you can also perform pretty much all ReLive VR configuration tasks via a web browser, just like you would configure a router, which I think would be more convenient in your setup. Please refer to this [Wiki page](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Configuration-Using-a-Web-Browser) for details on how to enable this feature.
