### ISSUE TITLE
AMD wvr driver is making my steamVR crash (exception c0000005)

### ISSUE THREAD

**Issue by furan0** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#36]
Hi there,

After enabling reLive vr in my radeon settings, steamVR is constantly booting in safeMode.
After analyzing the logs, it looks like amd wvr drivers is crashing steam vrserver.exe with an exception c0000005 (the logfile is generated buy steamVr system report) : 
[steamVr logs.txt](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4081476/steamVr.logs.txt)

I tried uninstaling and reinstalling the driver multiple times, both in radeon v 20.1.2 & v 19.12.2, made a clean install of steamvr without any other drivers than amd wvr and even installed it by hand  (with vrpathreg.exe) but with no luck.

Here is the log from AMDWirelessVR (from steam/logs) if it helps : 
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4081492/AMDWirelessVR.log)

Thanks for the help !

**Comment by MikhailAMD** [comment]
I assume you don't run in a virtual machine.
Two things: 
- please create and share dxdiag log: 
https://support.microsoft.com/en-ca/help/4028644/windows-open-and-run-dxdiagexe
- enable crash dump and share the dump from vrserver.exe. Here are the instructions:
https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by MikhailAMD** [comment]
Did you read this: https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/issues/33

**Comment by MikhailAMD** [comment]
Based on the log below SteamVR successfully activated amdwvr driver and started enulerate audio: 
- do you have any unusual audio software?
- did you ever run regular Vive or other HMD or wireless solution on this PC?

at Jan 18 2020 19:44:41.492 - Loaded server driver amdwvr (IServerTrackedDeviceProvider_004) from C:\Program Files\AMD\WVR\OpenVR\bin\win64\driver_amdwvr.dll
Sat Jan 18 2020 19:44:41.543 - AUDIO: Refreshing audio devices
Sat Jan 18 2020 19:44:41.599 - AUDIO: Detected 35 playback and 51 record devices
Sat Jan 18 2020 19:44:41.699 - Exception c0000005

**Comment by furan0** [comment]
Thanks for the really fast reply !

Yes I'm not on a virtual machine.

Here are the dxdiag and crash dump : [DxDiag.txt](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4081674/DxDiag.txt) 
[vrserver.exe.13628.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4081690/vrserver.exe.13628.zip) (I'm not sure the dump is the full dump instead of the minimal, I can generate a new one if needed)

I read issue #33. I had the same think too but removed the ALVR line from openvrpaths.vrpath already.

For the Audio driver, It seems I have realtek & AMD hd audio driver for the common driver, however I also have steam streaming as well as virtual desktop audio drivers (from an earlier installation of virtual desktop) alongside. I tried disabling the virtual desktop audio driver but with no success.


The only other wired HMD I used on this system is the quest with oculus link.

**Comment by MikhailAMD** [comment]
Thanks for the dump. It really helped. We will fix the bug but to get around please create an empty text file with following path and name:
C:\Program Files (x86)\Steam\config\chaperone_info.vrchap
The file is normally created by SteamVR when you try run Room setup.  You may try to do so in Safe mode.
You should eventually run room setup with all default values and for height just enter 170.

**Comment by MikhailAMD** [comment]
Thanks for the dump. it was very helpful. We will fix the bug but to get around please unzip and copy this file [chaperone_info.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4081771/chaperone_info.zip)
to this folder: C:\Program Files (x86)\Steam\config\

**Comment by furan0** [comment]
That solved the issue, thanks again !
