### ISSUE TITLE
Issues connecting to quest via mesh router

### ISSUE THREAD

**Issue by liucidity** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#37]
Hi team, 

i use a mesh router and i seem to have trouble connecting. 

i have referred to the advanced network guide and tried the fixes.
the Deco M5 seems to not allow me to change individual IP's in its firmware

**Comment by MikhailAMD** [comment]
Let’s start with simple things:
1.	Ensure that on PC your network connection is marked as “private” or as “domain” (and not as “public”)
2.	Try temporarily disable firewall on your PC. Restore if not helped. If helped, configure your firewall for vrserver.exe.
3.	Ensure that on the PC you have a single network connection. To check that, start command line window. Type the command below. Zip ipconfig.txt and share with us. If you see additional unused network adapters, disable them in Device Manager.
ipconfig > ipconfig.txt 
4.	Log into your router, find Quest IP address. Compare it with IP address of PC from ipconfig. Does the Quest IP address is in the same subnet as PC IP address?
5.	On PC in command line window execute this command:
ping <Quest_IP_address>
Does the device respond?
6.	Install ADB. See this guide for details: https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Setting-up-ReLive-VR . Connect your Quest via USB cable to the PC. Start command line where adb.exe is available. Execute commands:
adb.exe shell
ping <PC_IP_Address> 
Does PC respond?
7.	Try to connect, close SteamVR and share this file with us: c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log

**Comment by GennadiyAMD** [comment]
@liucidity - if you end up having the headset and the PC on different IP subnets and cannot change that, you can force connection to the specific IP address of your server. Please refer to the last section of this 
[Wiki page](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Network-Setup) for details.
