### ISSUE TITLE
Rise of the tomb raider VR (Blood ties DLC) way too dark

### ISSUE THREAD

**Issue by sofaplayer2** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#38]
Hi,

I was testing this game on the quest through AMD Relive and the game looks way too dark on the headset, however on the pc screen (the mirror when playing in VR) looks fine. It is basically black apart from the light sources, which illuminate a little area around them (like 1 to foot around them)

I tried it with the oculus link and the game looks fine there, same than on the PC while playing.

I'm using the latest client with the Adrenalin 2020 Edition 20.1.3 driver, on windows 10 x64.

I haven't tried to change the encoder, I left it on auto.

If there's anything I can do to troubleshoot, let me know.

Thanks in advance.

**Comment by sofaplayer2** [comment]
I've found a similar issue in another game:

Yay! it works! i have found new setting 10BitSRGB, it was false by default, setting it to true fixes dark scenes in Echo Arena. Didnt noticed how it impact other titles yet, but thank u guys, u are awesome!
--
I'll try this when i get home and update it with results.

**Comment by MikhailAMD** [comment]
Yes, this option was added specifically for such cases to correct unusual usage of 10-bit surfaces. Most of VR games render into 8-bit surfaces so they should not be affected.

**Comment by sofaplayer2** [comment]
Hi,

I can confirm this option fixed the issue.

Thanks a lot.
