### ISSUE TITLE
Stuttering every 3-4 minutes

### ISSUE THREAD

**Issue by eduwp90** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#39]
Hello there.

I've been using ReLive VR for a while now and it works great but I have some occassional stuttering every 3-4 minutes. The stutters look like a massive drop of frames and some artifacting for 3 seconds.

My pc specs are:

i7 4770k @ 4.3Ghz
16gb 1600 RAM
Vega 56
W10 Pro 1909
Adrenalin 2020 20.1.3 (Clean install with DDU)

Im streaming to an oculus quest, with a wifi ac router. 5Ghz SSID isolated on the 80 MHz bandwith. No issues at all except for that stuttering.

Things that I've tried:

Replaced the router with another ac, same configuration and the issue persists. Also noticed that if I stream to a tv using steam link, the issue replicates on the TV at the same time that is happening on the quest. This let's me think

 that the problem is on the PC side.

Monitoring the resources looking for cpu/gpu spikes didn't tell anything as they don't even reach 70%. Also the stuttering happens with demanding games and non-demanding apps.

Any clue? Attaching the settings.json config file here.
[settings.json.txt](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4145529/settings.json.txt)

**Comment by MikhailAMD** [comment]
Here are few random thoughts:
- Massive frame loss points to a WiFi issue. It could be router or PC, even while you tried a different router. You may want to check if your router uses a WiFi channel which overlaps with someone else.  I use "WiFi monitor" app on Android phone to check what is around me. If you find an overlap, you can assign a particular channel in the router setup rather then use automatic settings.
- Try to switch to TCP. In the "setting.json" replace "UDP" with "TCP" and reconnect. 
- Watch network traffic for spikes on PC in Task Manager- maybe some app periodically messes up with network traffic.
- Check in the router pages if other devices are connected and switch them off one by one.

**Comment by eduwp90** [comment]
Thanks for your fast response Mikhail. When creating the VR exclusive SSID I checked the availability of the channels. I used 36 & 44 because nobody was using them so I discard that.

I'll try to change the settings to TCP and monitor my network better and reach out to you.

**Comment by eduwp90** [comment]
Well after trying different configurations with no sucess, I found some posts with people having the same issue, but with Virtual Desktop. (It is a known issue).
The solution is to switch the bandwith from 80 Hz to 40Hz.

I tried oit and the problems are gone. Only downside is that the transfer speed goes from 800+ mbps to "only" 400mbps but i found this enough.

IDK if this a headset issue or a streaming issue, maybe the radeon team want to take a look?

**Comment by GennadiyAMD** [comment]
@eduwp90 - thank you so much for providing this feedback! We have updated the [Advanced Network Setup Wiki page](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Network-Setup) based on your feedback and some additional research.
