### ISSUE TITLE
Quest menu button doesn't open SteamVR menu

### ISSUE THREAD

**Issue by robkelly** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#4]
All the other buttons and controls work as expected, but the hamburger menu button on the left controller doesn't open up the SteamVR menu. 

Looks like I'm not the only case of this: https://www.reddit.com/r/OculusQuest/comments/c3d6kq/amd_now_has_a_solution_for_streaming_vr_games/err7ow5/

**Comment by GennadiyAMD** [comment]
Thanks for reporting this, will investigate.

**Comment by GennadiyAMD** [comment]
Fixed in 1.0.10 version of the APK

**Comment by robkelly** [comment]
Confirmed fixed. Thanks!
