### ISSUE TITLE
No audio when using Relive

### ISSUE THREAD

**Issue by rade0** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#41]
First off thanks to AMD for this amazing bit of software!

Game video stream really well to my headset, the only issue is that my there’s no sound. 

I have tried following the suggestions in a similar issue (edit if the text file in the app data dir) but to no avail.

One thing I did notice is people saying that you need to select “Stream Streaming Audio” as the sound device but I don’t have this specific option, the closest being the oculus virtual headphones which I have selected.

Does anyone have any suggestions to get the sound working? Have I missed something or is it an issue with the software on my specific configuration?

Thank you in advance for any info.

**Comment by MikhailAMD** [comment]
Please check this troubleshooting guide. It has Audio section.
https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Troubleshooting
Please close SteamVR and share this log:
c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log

**Comment by rade0** [comment]
Thanks for the swift response, have just ran through it again to make sure and no joy. Please see attached log file as requested.
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4192061/AMDWirelessVR.log)

**Comment by MikhailAMD** [comment]
Audio looks fine in the log - no errors. Could you please check this:
1. Connect an audio headset to the PC audio output and ensure that you hear game audio. If it doesn't work, reconfigure audio outputs in Windows.
2. Some games stop playing audio when the game is not in foreground. Do you have Audio in SteamVR Home? 
3. Stupid question: do you hear audio in games running locally on Quest?
4. Do you have, by chance, other VR streaming solution installed at any time in the past?
5. Do you have by chance some audio streaming solution installed on your PC?

**Comment by rade0** [comment]
Thanks for the swift response, in answer to your questions:

1. Other audio devices work fine with games

2. No audio whatsoever, nether in steam home or in game

3. Yes normal games/oculus home sound is fine 

4. Yes, I had Virtual Desktop installed, which works nicely. I had tried closing it, and disabling the virtual audio device it creates as well.

5. No.

**Comment by GennadiyAMD** [comment]
@rade0 - try manually removing VD from %LOCALAPPDATA%\openvr\openvrpaths.vrpath. There's an array called external_drivers there and it will have a list of paths to external drivers that SteamVR loads. Leave just ReLive VR there, remove everything else, save the file, restart SteamVR and see if you get any sound.

**Comment by rade0** [comment]
Hi @GennadiyAMD Yes that was one of the first things I did as part of the trouble shooting:

```
{
	"config" : 
	[
		"C:\\Program Files (x86)\\Steam\\config"
	],
	"external_drivers" : 
	[
		"C:\\Program Files\\AMD\\WVR\\OpenVR"
	],
	"jsonid" : "vrpathreg",
	"log" : 
	[
		"C:\\Program Files (x86)\\Steam\\logs"
	],
	"runtime" : 
	[
		"C:\\Program Files (x86)\\Steam\\steamapps\\common\\SteamVR"
	],
	"version" : 1
}
```

**Comment by GennadiyAMD** [comment]
@rade0 - could you attach a dxdiag report? Just run `dxdiag` from the command line and click on the _Save All Information_ button. Attach the file it produces.

Thanks!

**Comment by rade0** [comment]
No problem, please see attached. Note that "Sound 2" ("Headphones (Oculus Virtual Device)") is the currently active output.

[DxDiag.txt](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4208993/DxDiag.txt)

**Comment by MikhailAMD** [comment]
Could you please try to make the LG TV the default audio device and ensure that audio goes there. Then restart SteamVR and try.

**Comment by rade0** [comment]
That’s done the trick! Thanks for your support :)
