### ISSUE TITLE
Feature Request: black screen problem

### ISSUE THREAD

**Issue by YukihoAA** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#46]
Hi, I'm using Oculus Quest with AMD ReLive for VR.

Sometime with playing VRChat, 
Quest shows black filled frame if VRChat have some frame drop.

Traditionally, if there is some packet lost or frame drop, we just shows previous frame that is drown before.
But ReLive VR app in Oculus Quest shows just black screen instead of it.

It cause black screen splashing which is very uncomfortable.

I suggest to show previous frame if there is no proceed frame to show it.

Thank you for making this wonderful feature.

Hardware:
HMD: Oculus Quest 64GB
CPU: AMD Ryzen 7 2700X
RAM: 16GB
M/B: MSI B450M MORTAR
VGA: SAPPHIRE RADEON RX590 NITRO+
AP: ipTime A2004NS-MU (802.11ac, 5Ghz with 80Mhz channels, Connected by Cat.6)

**Comment by GennadiyAMD** [comment]
@YukihoAA - thanks for the feedback!

ReLive VR does not insert any black frames, it does exactly what you've described. So I suspect it's an issue with VRChat itself or something else.

Do you see the same problem with other content?
How frequently does it happen?
Could you please share the log: c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log

As one of the suggestions in the meantime, try reducing the channel width in your router from 80MHz down to 40MHz or just set it to Auto, see if it makes any difference.

Thanks!
