### ISSUE TITLE
Oculus Quest - Gesture and grip/trigger buttons are not working with Half-Life Alyx

### ISSUE THREAD

**Issue by TehFreeDoM** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#47]
When I play Half-life Alyx using ReLive I'm stuck with the default, "open hand" (see attached). Pressing in the trigger or grip button does nothing, nor does the finger tracking with the thumb or index finger. It does work properly when I use the Link cable+Oculus App to load SteamVR & Alyx. 

Troubleshooting steps I've completed so far:
- I'm using the current AMD Drivers (20.3.1) and I have done a fresh install
- Using ReLiveVR-Oculus-1.0.23.apk, also reinstalled
- I'm using SteamVR beta 1.11.3
- Quest is updated to version 14 (latest it allows)
- Tried various SteamVR controller bindings
- AMD Radeon settings controller settings are set for Rift S (also tried CV1)
- All the buttons are mapped and responsive in the 'Test Controller' settings in SteamVR
 

Any suggestions?

![com amd wirelesshmd-20200329-130448](https://user-images.githubusercontent.com/62851546/77858423-adb1ed80-71c0-11ea-9fc5-726acb9e4359.jpg)

**Comment by GennadiyAMD** [comment]
@TehFreeDoM - Could you please try switching emulation to one of the HTC headsets and see if this makes a difference? We've seen games that default to Oculus native API rather than OpenVR when they see an Oculus headset.

Do hands move at all?

**Comment by TehFreeDoM** [comment]
The hands will automatically move/grip/point when it comes into contact with something that is interactive, I believe that's the way the game is designed. I tried the Vive and Vive Pro, The trigger button seemed to be remapped as a grip and does cause the hand to clench. It's unplayable otherwise though, none of the other buttons work and neither do the gestures..

**Comment by xecollons** [comment]
I had a similar problem yesterday: pressing the trigger doesn't do the "grab"/"close fist" animation. But I could grab things when I had my hands near an interactive object.

**Comment by 0rford** [comment]
I’ve had a similar problem with other mainly Walking dead. In the Steam game directory for have life, have a look for a file that has the control config settings, the issue I had there was two entries for Oculus, one was empty so I copied and pasted the contents to the empty one. For some reason not matter what I did in Steam the controls would always use the empty controls config file until I copied over the settings.
 I’m not saying Half Life is the same but I hope it helps.

**Comment by maybeageek** [comment]
I am having this exact "problem".

"" because the game is absolutly playable, I can grab and manipulate stuff ingame, no problem. Just the animation is not working. 

Driver 20.4.1
ReLiveVR-Oculus-1.0.23.apk
SteamVR 1.10.32
Quest: V15

**Comment by GennadiyAMD** [comment]
@maybeageek , @0rford, @xecollons, @TehFreeDoM  - the latest update to the game posted today by Valve has resolved the issue with controllers. Please download it from Steam.

Thanks everyone for reporting this!

**Comment by physiohealth1979** [comment]
I'm having the same problem. I can play well, but my hands won't close, and it feels like I have less strength to lift objects. This problem also occurs with other games (like the "Of Lies and Rain" demo). Has anyone here solved it? If so, how?
