### ISSUE TITLE
Oculus Quest - Grey screen in some games

### ISSUE THREAD

**Issue by xecollons** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#48]
I tried ReLive VR yesterday, and at first it started working well, showing Steam Home and so. The problem came when I launched my first game: Elite: Dangerous. It seemed to start, the music was playing on the visor, but all that I saw was a lot of... grey. All the screen was grey.

I tried later with a couple of more games, Tabletop Simulator and Cosmic Flow and they worked like intended.

I tried with Subnautica later, and the same as before: grey screen, music playing. I took a peek at my computer's monitor and the image was moving as I moved the visor, so it seemed that the game was tracking the movement.

I tried Alyx laster, and went well except for some little problems inside the game, but that's another story.

Summarizing, I tried 5 games yesterday: Elite, Tabletop, CosmicFlow, Subnautica and HL: Alyx. 2 of them showed a grey screen.

I used 20.3.1 drivers, SteamVR is at version 1.10.32, and the glasses firmware is the latest I think, they're new and I updated them yesterday.
They're connected to a 5G wifi, and my PC is connected with a Ethernet cable.

It's something on my end? Is it something general? Do we have a compatibility list or anything like that?

Thanks.

**Comment by quakemazer** [comment]
Elite works for me over Relive. 

The only thing I can suggest trying is to start the Relive app on your headset, and then launch Elite through Steam (take the headest off and launch it on the computer, in steam library, play game, select the option Elite Dangerous in Steam VR mode.) as opposed to launching it from inside VR.

Might not work but it's something to try. 

Also note that Elite's loading screen is static inside the headset until the main menu loads. You'll probably have to hit F12 to recenter the headset when you get comfortable at the desk. You also need to use physical controls (the touch controllers won't work in game). I use keyboard and Logitech joystick.

Good luck.

**Comment by xecollons** [comment]
Yeah, I have tried to restart Relive and I launched ReLive through Steam. Didn't work. I can try the F12 thing, but when I took off the headset, the menu was loaded on my screen.

Thanks for the reply.

**Comment by GennadiyAMD** [comment]
@xecollons, @quakemazer : Please make sure you perform Room Setup for standing experience. We've seen some games that refused to work without doing room setup and exhibited some really weird behavior until Room Setup was performed, while for others it didn't matter.

**Comment by xecollons** [comment]
@GennadiyAMD That was it! I didn't calibrate my room at first, and since some games worked, I did not think more about it.

Many thanks! I'll close the issue.
