### ISSUE TITLE
Feature Request: Slider for Bitrate

### ISSUE THREAD

**Issue by Cmonpo** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#49]
I’m really happy with the relive vr experience, but I think it will be awesome to have a slider to choose the bitrate I want to use. Between 50Mbps and 100Mbps there’s a huge gap and with some routers it will be useful to be able to select 75Mbps or 80Mbps.
I’ve tried changing it from the settings file but it does not seem to work.
Any chance to add this option on the future?

**Comment by MikhailAMD** [comment]
The settings file should work. 
- What did you put? 
- How did you check? 
- Share the file. 
Network Monitor in Task Manager will give rough idea. 
There is an advanced configuration options via the settings file you mentioned or via web browser interface. You can set any bitrate in reasonable limits - all in bits. But the Web interface just writes to the settings file.
https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Configuration-Using-a-Web-Browser

**Comment by Cmonpo** [comment]
Sorry, I didn't know I could use the web interface to edit the settings. I've tried it and works flawless!!
Thankyou very much!
