### ISSUE TITLE
After Update to Oculus Quest v16 only a grey or black screen appears

### ISSUE THREAD

**Issue by MisterHighping** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#50]
FOUND THE SOLUTION: The MTU Size of 9014 is a problem for the Oculus Rift. Just use the default frame size.

############################################################################

Hello everybody,

with the Update 16 of the Oculus Quest I can't use AMD Relive VR anymore. I just get a Dark or Grey Square in Front of me when I start SteamVR and nothing more happens.
When I look at my PC display I see that Steam is recognizing the movements of my headset and the controllers but neither the sound nor the video streams appear on my Oculus Quest.
I am using ReLive VR in the newest version and the AMD Driver 20.4.2.

Thank you very much and best regards,

**Comment by GennadiyAMD** [comment]
@MisterHighping - thanks for posting a solution. Are you referring to the datagram size in settings.json or settings in your router/NIC in the PC?

**Comment by eywhat** [comment]
And what is MTU ??? Can anyone explain to me? I have no problems with ReliveVR. I use the new menu from the Quest. In the beginning, although Relive was installed on the quest, the app was no longer displayed in the app menu after the update to version16. After uninstalling ReliveVR and reinstalling via Sidequest, everything worked again.

**Comment by GennadiyAMD** [comment]
@eywhat - MTU stands for "maximum transmission unit". Simply put, when you send something over Ethernet or WiFi, your network card would send out a packet of a fixed size. When your message is shorter than the MTU, it would still send the MTU number of bytes. When it's bigger than the MTU, it would be broken down into multiple packets of MTU size each. Wikipedia has a good [article](https://en.wikipedia.org/wiki/Maximum_transmission_unit) explaining this. MTU is the property of the lowest (physical) layer of the protocol stack.

On top of this physical layer, there's IP and on top of IP there's TCP and UDP. UDP is also a packet-oriented transport, where a datagram is the transmission unit. Each message is sent across the network as one or more UDP datagrams. UDP datagrams are also restricted in size and this is what the DatagramSize parameter in settings.json controls. You can read more about it [here](https://en.wikipedia.org/wiki/User_Datagram_Protocol#UDP_datagram_structure). 

The default MTU for Ethernet and WiFi is 1500 bytes. Diverging from the standard values might cause compatibility issues depending on the network equipment used. The maximum UDP datagram size is 65507 bytes and might need to be smaller when there are routers between the headset and the PC or when your router cannot support larger sized UDP datagrams. Generally, we recommend to leave these values at default unless there's a good reason to change them.

Hope this clarifies it somewhat.
