### ISSUE TITLE
ReVive doesnt work

### ISSUE THREAD

**Issue by DicciusMaximus** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#53]
ReVive games either crash (Boneworks+), the controllers dont work (Blade and Sorcery), or the gamma doesnt work right (EchoVR)

**Comment by GennadiyAMD** [comment]
@DicciusMaximus - for EchoVR being too dark we added a parameter to settings.json: 10BitSRG. It is set to false by default, but for games like EchoVR, that don't handle 10bit sRGB according to the standard, you can set it to true. 

Could you please provide more details on the controllers issue with Blade and Sourcery? Could you also try switching headset emulation to one of the HTC Vive options when playing Boneworks and Blade&Sorcery to see if this would resolve any of the issues? Thanks!

**Comment by cmcosta81** [comment]
> @DicciusMaximus - for EchoVR being too dark we added a parameter to settings.json: 10BitSRG. It is set to false by default, but for games like EchoVR, that don't handle 10bit sRGB according to the standard, you can set it to true.
> 
> Could you please provide more details on the controllers issue with Blade and Sourcery? Could you also try switching headset emulation to one of the HTC Vive options when playing Boneworks and Blade&Sorcery to see if this would resolve any of the issues? Thanks!

Echo VR is in open beta (free for anyone to download on Quest) I'd suggest playing native Quest version for Quest owners, and not have to worry as much about latency issues or this.

**Comment by DicciusMaximus** [comment]
@GennadiyAMD  TOuch contollers. I tried the Vive Controllers and nadda. With blade and sorcery the controllers get stuck wherever they were. with boneworks he just t poses

**Comment by GennadiyAMD** [comment]
@DicciusMaximus - just tried Blade & Sorcery from Steam (no Revive needed) and it worked fine with controllers being emulated as Rift S. All hand movements including fingers were as expected. So it seems that you're seeing a Revive issue here.

Not sure I understand what you meant with "with boneworks he just t poses"? We've seen an issue with Boneworks when hands appear stretched out when emulating Rift. Haven't figured it out yet, But no crashes though.

**Comment by DicciusMaximus** [comment]
I don't think you understand. I have blade & sorcery on Oculus software from when I used to play it on there and it doesn't seem to work

**Comment by GennadiyAMD** [comment]
@DicciusMaximus - I understand perfectly well, you want to play the Oculus-only version under Revive. What I'm saying is that I tried to exclude Revive from the picture to narrow it down. It not working under ReVive seems to be caused either by Revive itself, or the game being purposely designed to work directly with the Oculus runtime only, because the Steam version of the same game works correctly, recognizing ReLive VR as Oculus Rift S. I realize that this doesn't solve your issue though.
