### ISSUE TITLE
Can't perform room setup.

### ISSUE THREAD

**Issue by Kenjiftw** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#54]
I can't get passed the room setup because my oculus go is not detected by steamvr. Is it normal? Or it must have already been detected by this point?

**Comment by GennadiyAMD** [comment]
@Kenjiftw - do you see the WiFi icon for the headset in SteamVR? Or it looks like something else? If you see the WiFi one, but it's grey, just cover the proximity sensor with your finger for it to turn green and hold it covered until you enter Room Setup. You can do room setup for Standing Experience only as room scale expects lighthouses.

**Comment by MarcoWilli** [comment]
Same problem here on Lenovo Mirage Solo (6DOF).
Headset is workin and also shown "active" symbols in SteamVR status window but within room setup it says that it´s off. Applies to standing experience and room scale.

**Comment by MarcoWilli** [comment]
Update:
I reinstalled/removed everything VR related. Steam/SteamVR twice. Graphics driver.
But still getting "external driver" entries in the Steam logs that really shouldn´t be there anymore. So I guess there is some kind of "settings synchronisation" of Steam going on or similar and this isn´t a ReLive issue - at least in my case.

**Comment by GennadiyAMD** [comment]
@MarcoWilli - You can manually edit the %LOCALAPPDATA%\openvr\openvrpaths.vrpath to remove all unwanted drivers - Steam loads everything from there. It's just a JSON file with the external_drivers array listing them all.

Daydream controller is better emulated with an HTC Vive or Vive Pro:
- Trackpad: clicking upper 20% of trackpad is clicking "trigger" button, clicking lower 80% of trackpad is clicking "trackpad" button
- App button: On click ( < 0.3 seconds) this button generates app click, On press ( > 0.3 seconds) this button generates system press
- Home button: Isn’t mapped to anything, clicking will take user back to Daydream home screen when pressed.

Not a full equivalent, but this is the best we could do with the little controller with almost no buttons.

**Comment by MarcoWilli** [comment]
Great! I was not able to find specifically THAT information of settings file anywhere! Thanks!

But still, I can not perform room setup with that headset and ReLive without any 3rd party tools.

I tried again:
Blocking the tracking cameras for a while seems to put the hmd into 3DOF mode. THEN it is possible, to perform room setup (the hmd symbol changes in SteamVR status window, too). But it is different to 6DOF room setup as it seems like the hmd stays registered as 3DOF inside SteamVR - allowing no movement and no following 6DOF re-calibration/room setup afterwards.

So something here seems not to be handled properly and I am not able to fix this on my own.

I am wondering though, as I read on various sites that ReLive has been made "especially" for 6DOF headsets like Mirage Solo and Vive Cosmos?!

**Comment by GennadiyAMD** [comment]
@MarcoWilli - why are you blocking the tracking cameras? Cover the **proximity sensor** - the little black window on the inner side of the headset, right between the lenses you look through. This has nothing to do with 6DoF tracking, all this sensor does is detecting whether the headset is on your head. When you have a wired headset, there is a difference between it being connected to the PC and it being on your head - the Room setup wizard can still see the wired headset even when you're not wearing it. But all standalone headsets just fall asleep when you take them off and stop communicating completely. So you need to keep the sensor covered so that SteamVR keeps seeing the headset when the Room Setup wizard starts. Once it starts and detects the headset, you should be able to perform room setup.

You can only perform it for Standing experience as the room scale setup relies on lighthouses for tracking, which you don't have with the inside-out tracking of a standalone headset. You can still move around, but your tracking is not absolute - it will start at (0,0,0) where you put the headset on.

**Comment by MarcoWilli** [comment]
Sorry, that I did not state that clear enough. Of course I tried to do room setup with the headset wearing or at least covering the proximity sensor.

So in all:
No room setup (both methods) possible with clean setup, covered proximity setup or wearing the hmd. Tried different config settings for in steamvr.vrsettings but with no success.

**Comment by GennadiyAMD** [comment]
@MarcoWilli - this is rather strange. I've just performed room setup with my Mirage Solo using both methods and it worked fine. Judging by the screenshot, you have the same version of SteamVR. Am I understanding correctly that the Next button never gets enabled in your case, it's always greyed out and that's the problem you're having?

**Comment by MarcoWilli** [comment]
Yes, you are right. I am not able. I even did a reinstall of Steam, SteamVR and AMD drivers AND did a reset of the hmd to avoid developer/beta settings may be a reason for this problem. Nothing helped. Tried SteamVR beta version, too. Tried manual settings eg enabling/disabling multipledriverallow, null driver, etc. (then clean reinstalled Steam/VR afterwards again).

As written, just by accident I found out that when the cameras are covered for a while the hmd disables tracking and then goes into 3DOF mode (or similar) and that way room setup is possible but not usable.

Maybe we are having different firmwares on the device itself?
You are able to perform room scale setup aswell??? Are you using the 6DOF controller developer kit?

**Comment by MarcoWilli** [comment]
I figured out, why it did not work:
You CAN´T do the room setup from within the headset! As soon as you switch "out" of the room setup to the desktop view (like I did on the screenshot) the hmd becomes "off".

How am I supposed to KNOW this?? ^^
I wanted to do everything within the hmd (except entering the height) without having to move everytime between my rooms and therefore the desktop view is really handy...
