### ISSUE TITLE
 Radeon-ReLive-VR README.md typo

### ISSUE THREAD

**Issue by WarGamezz** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#58]
Hey everyone :) First of all I'd love to thank you for creating that project and making wireless VR experience that much better. It's not really big issue. I just wanted to point out that the README.md still points to the version 1.0.20 causing redirect to 404. I mean you can always get the correct apk by checking commits :) 

Cheers!
Marc

**Comment by GennadiyAMD** [comment]
@WarGamezz - thanks for catching the typo and for your kind words. The typo has been fixed.
