### ISSUE TITLE
Distortion/stretching on Quest

### ISSUE THREAD

**Issue by RaymondWeilacher** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#6]
Hi, I'm experiencing distortion on the Oculus quest when I'm running Relive. It's noticeable when I turn my head. I'm using the CV1 profile. I believe it's due to the resolution differences between CV1 and Quest. I've tried manually changing the EyeResolution in the settings.json file to 1440 x 1600. That didn't help though. Thanks for this awesome feature!

**Comment by GennadiyAMD** [comment]
@RaymondWeilacher - thanks for reporting this and please try APK version 1.0.12. Please let us know if you see an improvement. It had nothing to do with EyeResolution in settings.json - I'd suggest leaving these values at defaults. If you need to roll back the changes but haven't saved the original settings.json, simply delete it and it will get re-created with defaults next time you launch SteamVR. You will need to change the headset profile back to "Oculus Rift CV1" though.

**Comment by RaymondWeilacher** [comment]
Much improved, thank you! Getting better performance than ALVR and much easier to use.
