### ISSUE TITLE
HeadSet not detected

### ISSUE THREAD

**Issue by exander77** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#60]
How to troubleshoot this? I have everything installed, but headset is not detected. Virtual Desktop works fine.

In HeadSet there is a black WiFi icon.

**Comment by JpTiger** [comment]
Not part of dev, and you've likely already tried this, but just in case: have you tried launching SteamVR on your computer when the black wifi icon is displayed in your headset?

**Comment by GennadiyAMD** [comment]
@exander77 - is SteamVR showing the WiFi icon for the headset? If not, you probably have Virtual Desktop running for the server and that's what's listening for the incoming connections.

If yes, then check your firewall. A common problem is that your network type is set to Public and the firewall is open for Private  and Domain networks only.

**Comment by GennadiyAMD** [comment]
@JpTiger - yes, of course we have. It's supposed to connect no matter what the launch order is. The headset is continuously looking for servers. Is there a problem?

**Comment by JpTiger** [comment]
No on this issue from my end - my tip was for the OP

**Comment by GennadiyAMD** [comment]
@exander77 - have you been able to resolve the issue or do you need further help?
