### ISSUE TITLE
A listing on SideQuest for Oculus Quest/Go

### ISSUE THREAD

**Issue by sidequestlegend** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#61]
Who would i talk to about adding this to [SideQuest](https://sidequestvr.com)?

I'm Shane and I run SideQuest. I've had several users ask for this to be on there and i can link direct to the apk in this repo. I will go ahead and create a convenience listing for it tomorrow and i can transfer it to someone else or remove it on request. 

Thanks!

**Comment by GennadiyAMD** [comment]
[AMD Official Use Only - Internal Distribution Only]

Hi Shane,

Please email me directly at gennadiy dot kolesnik at amd dot com, we can discuss.

Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GennadiyAMD** [comment]
@sidequestlegend - Hi Shane,

It's up and live. Thank you!

**Comment by sidequestlegend** [comment]
Great!
