### ISSUE TITLE
Cannot Do SteamVR Room Setup(quest)

### ISSUE THREAD

**Issue by Leoniduc** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#63]
Stuck at establish tracking. Tried covering the proximity sensor, nothing. Headset is stuck at white screen with an animated wireless signal, SteamVR will not start without doing a room setup.

**Comment by GennadiyAMD** [comment]
@Leoniduc - do you see the WiFi icon in the SteamVR window (on the PC, not in the headset)? If yes, did you get a popup from Windows Firewall when you first ran SteamVR? If yes, check your network type, it is likely set to Public and you probably just clicked on OK in that popup - change your network to Private.
If you don't see the WiFi icon in SteamVR, then you probably have another streamer app (Virtual Desktop, ALVR, Riftcat) installed at the same time and they take over SteamVR before ReLive VR or you haven't enabled SteamVR integration in Radeon Settings. 
Check what you have in <you user directory>\AppData\Local\openvr\openvrpaths.vrpath, in the external_driver section. Try removing everything other than ReLive VR.

[This](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Troubleshooting) might be helpful.

**Comment by Leoniduc** [comment]
Okay, so it turns out ReLive's not even mentioned in my openvrpaths.vrpath file. I removed Virtual Desktop and Riftcat from the file and am still getting the issue. Firewall is set to all for steamvr servers and relive software, and while I am getting the wireless icon on steamVR, it's only green temporarily when SteamVR activates and remains grey throughout the rest of the process.

**Comment by GennadiyAMD** [comment]
@Leoniduc - I'm a little confused. You're saying that ReLive is not even mentioned in openvrpaths.vrpath, but at the same time you see the WiFi icon in SteamVR. The openvrpaths.vrpath file is the only place that tells SteamVR to load ReLive...

So, let's do this:
1. Open Radeo Settings, click on the gear icon in the upper right corner that says Settings in the tooltip, then click on the General tab, scroll down and flip the SteamVR Integration switch in the VR Streaming section to 'Enabled'. Alternatively you can just double-click on the c:\Program Files\AMD\WVR\OpenVR\registerdriver.cmd, this would do the same thing. After that ReLive VR should appear in openvrpaths.vrpath.
2. Start SteamVR
3. Start the ReLive app on the headset. It should connect and the WiFi icon in SteamVR should go green and you should see the default Steam VR scene and eventually Steam Home.
4. Without exiting the ReLive VR app on the headset, just take it off, cover the proximity sensor with your finger and start Room setup. Once it starts, you can let go off the proximity sensor. Do the Standing/sitting experience setup only, not room scale.

**Comment by Leoniduc** [comment]
Okay, so my openvrpaths.vrpath file looks like this currently: 
{
	"config" : 
	[
		"C:\\Program Files (x86)\\Steam\\config"
	],
	"external_drivers" : 
	[
		"C:\\Program Files\\AMD\\WVR\\OpenVR"
	],
	"jsonid" : "vrpathreg",
	"log" : 
	[
		"C:\\Program Files (x86)\\Steam\\logs"
	],
	"runtime" : 
	[
		"C:\\Program Files (x86)\\Steam\\steamapps\\common\\SteamVR"
	],
	"version" : 1
}


When I start SteamVR and then ReLive on the quest, the wireless icon goes green. As soon as I enter room setup, it goes grey and I cannot get past the "place the headset in an area that is visible to the sensors" part of room setup. The headset displays the white background and animated wireless icon, and steamVR displays "Waiting..." and a grey wireless icon .

**Comment by Leoniduc** [comment]
And the problem somehow seemed to resolve itself. I have no idea, what I did any differently but after giving up for an hour or so I gave it another try and it's working flawlessly now. I wish I could provide more info on what changed
