### ISSUE TITLE
Syncing SteamVR Play Area with Oculus Quest Guardian Boundary

### ISSUE THREAD

**Issue by lewistham9x** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#65]
While playing Half Life Alyx, among other VR games, I noticed a bug where the SteamVR play area and Oculus Quest guardian boundary which I initially matched together manually would go out of sync, where SteamVR's play area rotates in a different direction from Quest's. This becomes very frustrating as I have to deal with a false play area from SteamVR, while viewing Quest's guardian boundary.

I heard that SteamVR by default manages to synchronise itself with Guardian. Would this be possible with streaming over Radeon Relive VR?

**Comment by GennadiyAMD** [comment]
@lewistham9x - unfortunately no. There's no API available from Oculus to read its guardian parameters. But why not turn off the guardian in SteamVR and rely on the one in the Quest?

**Comment by lewistham9x** [comment]
Great idea, it works fine now 👍
