### ISSUE TITLE
No audio in SteamVR with ReLive

### ISSUE THREAD

**Issue by overdrive-ostrich** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#66]
Video works great, but I'm not getting any audio in SteamVR. I have tried the steps found in: https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Troubleshooting

I did have Virtual Desktop installed previously, but I removed it, uninstalled the drivers, and deleted it from %LOCALAPPDATA%\openvr\openvrpaths.vrpath

[DxDiag.txt](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4939889/DxDiag.txt)
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4939892/AMDWirelessVR.log)

**Comment by GennadiyAMD** [comment]
@overdrive-ostrich - your default audio output is 6-channel. Try switching to 2 channel stereo.

**Comment by overdrive-ostrich** [comment]
That seemed to do the trick! I also uninstalled and reinstalled SteamVR to get rid of any Virtual Desktop files that might have stuck around.

So I guess I have to set my default audio to stereo every time. Is there any way to reset it back to 6-channel when I'm done, or will I have to do it manually every time?

**Comment by overdrive-ostrich** [comment]
Sounds like a good workaround. Thanks!
