### ISSUE TITLE
Please support 4K streaming

### ISSUE THREAD

**Issue by comienzo2093** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#7]
Hello, This app supports only 1440p. I hope this app supports at least 2160p. Is it impossible? Thank you for creating a great app. I am sorry if you feel uncomfortable because my English is not fluent.

**Comment by GennadiyAMD** [comment]
Hi @comienzo2093 

This resolution was selected to provide the optimal balance between image quality and latency/fps. On Navi you should be able to go higher. You can play with the EyeResolution (rendering resolution) and EncoderResolution parameters in the %LOCALAPPDATA%\AMD\OpenVR\settings\settings.json file and find the values that work for you. Note that each value for resolution is per eye.

If you want to go back to defaults, you can always delete this file and it will be recreated when you start SteamVR.

**Comment by comienzo2093** [comment]
You solved all my problems. Thank you very much. '당신의 앞날에 행운이 가득하길.'
This is the meaning of blessing in Korean. Have a nice day.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
19.
07. 09. 오전 10:31:56

2019년 7월 9일 (화) 오전 5:32, Gennadiy_AMD <notifications@github.com>님이 작성:

**Comment by romanpekarskiy** [comment]
@GennadiyAMD may i ask what is the main differences between Rx580 8gb and 5700/5700xt in terms of AMD ReLive VR streaming? Sorry, I cant find that information anywhere else.
Main issues i having its an stuttering for 1-2 secs as @comienzo2093 already noticed, and bad blocking artifacts in low-contrast scenes, for example Night Planet surfaces or deep space in Elite Dangerous. Latency is OK, but could i somehow upgrade image quality in terms of streaming if i switch to 5700 or 5700xt?

**Comment by romanpekarskiy** [comment]
@GennadiyAMD my router is Keenetic Viva, its pretty decent i think, Quest connected to 5ghz wifi in 866mpbs speed, PC connecter to router with cat.6 cable.
I was using 20/40/80 channels, and ill try to force router to work in forced one.
Im planning today to test Relive with new 19.9.1 drivers and ill let you know about my experience

**Comment by romanpekarskiy** [comment]
oh, sorry for misinformation, im using forced 36 channel all the time. with 20mhz bandwidth its too slow connection ~120mbps, swithing back to 20/40/80

**Comment by GennadiyAMD** [comment]
@romanpekarskiy - I'd suggest to force it to 80MHz. Also try to find a channel with the least amount of traffic from other APs around you and force the router to use it instead of leaving it at Auto. There might be some delays when the router starts hopping channels. 
Other devices using the same channel would still generate collisions, even when not connected to your router, as they still broadcast at the same frequencies.

**Comment by GennadiyAMD** [comment]
@romanpekarskiy - is this the router you're using? https://keenetic.ru/ru/keenetic-viva

**Comment by romanpekarskiy** [comment]
@GennadiyAMD yea, that is router im using.
I have checked my environment with android wifi scanner app, and seems like there are no one using 36 channel.
I have no any devices connected to 5ghz, and channel is forced to 36 instead of Auto.
