### ISSUE TITLE
SteamVR unable to find headset - no sign that Relive is working

### ISSUE THREAD

**Issue by Explosivekoala** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#70]
Latest driver - 20.7.2
Radeon Rx580

Activated integrate to Steam VR
Installed APK on oculus quest
Ethernet cable
Same frequency on quest

Activate steam vr - Searching for headset
No "Wifi" symbol - a headset symbol instead

In VR - infinited white loading screen with the searching icon

**Comment by GennadiyAMD** [comment]
@Explosivekoala - please attach the C:\Users\<your user name>\AppData\Local\openvr\openvrpaths.vrpath file. If you don't see the AppData folder, go to the View tab in Windows Explorer and check the Hidden items checkbox.

Also please check if you have the C:\Program Files\AMD\WVR\OpenVR folder and it's not empty.

**Comment by Explosivekoala** [comment]
Fixed it! Looked through old replies and deleted ALVR and IVRY from my openvrpaths file
Works like a charm!

I recommend adding it to the "Troubleshooting"
