### ISSUE TITLE
Relive periodically crashing - "Steamvr has encountered a critical error"

### ISSUE THREAD

**Issue by Explosivekoala** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#71]
Radeon Rx580 8GB

Half life alyx: Crashes entire PC. After 5mins playing :hard black screen - no response. Forced to restart pc

Boneworks - After a period of playing ~15 mins. 
"Steamvr has encountered a critical error" no error code or logs
No framerate issues or excessive artifacting

Have attached the "AMDWirelessVR"
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/5035832/AMDWirelessVR.log)

Love this service! Thank you guys so much for all your hard work.

**Comment by GennadiyAMD** [comment]
@Explosivekoala - are you seeing this crash with Half Life Alyx and Boneworks only, or other titles fail in a similar fashion as well? Is it consistently crashing at the same scene in the game? What driver version do you have? 

Could you also check if there are any graphics driver-related errors are logged in Event Viewer under Windows Logs/System (just type 'Event Viewer' in the Windows search box to launch it)?

Thanks!

**Comment by Explosivekoala** [comment]
It's not a regular event. It seems to be completely random / time related. 
My driver is 20.7.2

With event viewer: 
There were 2153 errors, all of which were : 

Log Name:      Microsoft-Windows-Kernel-EventTracing/Admin
Source:        Microsoft-Windows-Kernel-EventTracing
Date:          06/08/2020 19:24:18
Event ID:      2
Task Category: Session
Level:         Error
Keywords:      Session
User:          LOCAL SERVICE
Computer:      Haohua-PC
Description:
Session "OculusVadApoEventTrace" failed to start with the following error: 0xC0000035
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Kernel-EventTracing" Guid="{b675ec37-bdb6-4648-bc92-f3fdc74d3ca2}" />
    <EventID>2</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>2</Task>
    <Opcode>12</Opcode>
    <Keywords>0x8000000000000010</Keywords>
    <TimeCreated SystemTime="2020-08-06T18:24:18.959538200Z" />
    <EventRecordID>450590</EventRecordID>
    <Correlation />
    <Execution ProcessID="6260" ThreadID="18028" />
    <Channel>Microsoft-Windows-Kernel-EventTracing/Admin</Channel>
    <Computer>Haohua-PC</Computer>
    <Security UserID="S-1-5-19" />
  </System>
  <EventData>
    <Data Name="SessionName">OculusVadApoEventTrace</Data>
    <Data Name="FileName">
    </Data>
    <Data Name="ErrorCode">3221225525</Data>
    <Data Name="LoggingMode">2</Data>
  </EventData>
</Event>

I am unsure if this is GPU related but i saw oculus. Is there any key words I should be looking for?

Will test skyrim VR later today, in the process of downloading.

**Comment by Explosivekoala** [comment]
Also just found an issue with "OVRService Launcher, which occurred 4041 times: 

Log Name:      Application
Source:        OVRServiceLauncher
Date:          06/08/2020 14:52:56
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      Haohua-PC
Description:
The description for Event ID 0 from source OVRServiceLauncher cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

[LauncherService] Session change: New active session = 1


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="OVRServiceLauncher" />
    <EventID Qualifiers="0">0</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-08-06T13:52:56.189606000Z" />
    <EventRecordID>24556</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Haohua-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>[LauncherService] Session change: New active session = 1
</Data>
  </EventData>
</Event>

**Comment by Explosivekoala** [comment]
Skyrim VR Seems to work without issues

**Comment by GennadiyAMD** [comment]
@Explosivekoala - thanks for looking into this. We couldn't reproduce these issues on our end either. Try reinstalling the latest driver, but this time do a clean install (there's a Factory Reset checkbox on the first page of the driver installer, make sure to check it) - this would remove the current driver first. You should also try reinstalling the Oculus software - guessing here, but no idea how it might interfere. Also check if fans on the GPU and CPU are spinning when the game is running - overheating might cause random crashes anywhere in the system. 

We'll keep looking from our side. If you notice a pattern to reproduce it, please let us know, this would be helpful. Sorry, I know this is not the answer you're looking for...
