### ISSUE TITLE
Connects but shows a frozen image of SteamVR on the quest #67 +info +help request

### ISSUE THREAD

**Issue by xenoliferttv** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#74]
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/5184504/AMDWirelessVR.log)
_- same problem, additional info and help request_

Hey im from germany and have exactly the same issue as the guy who made a topic like this (see title).  **More germans likely have the same router** as me, hence its a default one for from Vodafone with Highspeed capabilities. 

**Specs:**

Rx 580, Ryzen 5 3600x, 16gb 3200mhz, 5ghz router with the ac thingie at the end.
I switched to 40mhz channel which is free around 6-8 channels to left and right. 1 mobile phone streaming music over 2.4ghz wifi atm. 100mb/s lan. EDIT: Without phone it works a little better, still same probs tho. EDIT²: switched lan to 1gb/s - no improvement. 

Router:

https://kabel.vodafone.de/static/media/Technicolor_VodafoneStation_CGA4233DE.pdf
Serialnr.
8CM2D299J700863
Firmware-Version
AR01.02.037.08_121719_711.PC20.10

and im running Malware Antibytes Pro as additional Firewall and security software.

Everything updated. 

**Problem:**

UDP SteamVR home would instantly freeze. 50mb/s - 100mb/s didnt change much.
TCP i could boot Beat Saber but the latency was everything but stable. It was jumpy as heck and disconnected every 1-2mins completly. Tracking worked fine on PC screen, disconnects happend on PC screen too.

Didnt had this problem with ALVR, however i think you guys have the better software on paper and i couldnt stream well with ALVR.
Everything uninstalled (SteamVR, ALVR and AMD Factory reset) deleting every trace i could fine. Im not sure i got everything regarding ALVR tho. Then fresh installed Ocolus Software, SteamVR and lastly ReLive when Link worked fine.

**So... how can i make this work? I would love to use ReLive!**

Why would ALVR would work but ReLive wont? Can i still use UDP without compromises, f.e. unlock some ports?

Im not to techsavvy and if you need anything else i will gladly provide you.

**Thanks for your awesome work <3**

**Comment by GennadiyAMD** [comment]
@xenoliferttv - answered in [the other thread](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/issues/67)

Also please try shutting down your Malware Antibytes firewall in case it's playing some tricks here.
