### ISSUE TITLE
Quest 2 support?

### ISSUE THREAD

**Issue by Cmonpo** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#78]
Are we getting a new app supporting the new quest 2 features?

**Comment by Dirro** [comment]
Would be nice + Working mic. 

But seeing how this hasn't been updated by AMD in 9 months it seems like this project is dead.

Hopefully @GennadiyAMD can say if this is still actively being supported or not but I doubt they're working on the VR side actively anymore.

Making users get a modmic to even be able to play Multiplayer/Steam is pretty major negative.

**Comment by GennadiyAMD** [comment]
@Cmonpo @Dirro - Quest2 support with 90Hz is coming very soon.

This project is most definitely **not** dead. We've heard the requests for mic support and are working on this.

**Comment by Cmonpo** [comment]
Really happy to hear that!!

**Comment by Dirro** [comment]
Yup great to hear that it's not abandoned.

Almost felt a regret for a moment going and buying a 6800XT and finding this dead versus Nvidias CloudXR.

Very soon hopefully means by sometime this month 😄

**Comment by GennadiyAMD** [comment]
@Dirro - much sooner than that, check it out now...

**Comment by paranoidandy** [comment]
Great news! Are there any other changes to ReLive in 20.12.1 other than Quest 2/90hz support? (Quest 1 here)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GennadiyAMD** [comment]
@paranoidandy - Quest2 90Hz support is entirely on the headset side. So if you don't want to update the driver and everything is working fine, then you don't really have to, if this is what you're asking.
