### ISSUE TITLE
App doesn't connect to PC with Ethernet on Quest 2

### ISSUE THREAD

**Issue by Espionage724** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#80]
Using a USB-C to Ethernet adapter on the Quest 2, I can connect it to Ethernet. However, the Relive VR app on the Quest 2 doesn't seem to make any attempt to connect with this set-up.

According to Oculus Home, Wifi is "connected" to an "unknown ssid", but really isn't connected to any wireless network. Browser and games can connect to the internet, and ALVR (PCVR streaming app) also works fine.

But Relive VR shows a HMD with a red X on it, instantly after starting the app. It doesn't seem like it tries to scan for computers or anything, and from my guess, it's not attempting to scan for computers because wifi isn't connected.

**Comment by GennadiyAMD** [comment]
@Espionage724 - ReLive is looking for a WiFi connection, there's an explicit check that is doing this. We could certainly remove it and I see no reason why it wouldn't work after that with the setup like yours. But I really wonder why you want to do this? Being wireless is certainly a benefit. The network component of latency isn't big to begin with, 6-7ms with a good router, most of the time is spent on rendering, encoding and decoding. Wired Ethernet could reduce it to 1-2ms (5ms gain), but that's without the USB dongle, which would add some of its own latency, depending on how well the dongle itself is implemented. I've seen some that would add more than 5 ms...

Not arguing your comment, just curious.

**Comment by Espionage724** [comment]
> ...But I really wonder why you want to do this?

No particular reason. I don't imagine I'd use it for any real usage, but was curious about testing it whenever I heard that the Quest 2 supported USB-C Ethernet adapters.

**Comment by Cmonpo** [comment]
If I'm not wrong, Ethernet adapters support was removed with the last upgrade (v23).

**Comment by GennadiyAMD** [comment]
@Cmonpo - you mean, the last update from Oculus?

**Comment by GennadiyAMD** [comment]
@Espionage724 - I'm going to close this since it's not really a supported feature, if you don't mind. Please feel free to reopen it if you think this is a valid use case and you'd want it supported.
