### ISSUE TITLE
Population One does not work with ReliveVR

### ISSUE THREAD

**Issue by eywhat** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#81]
Hello!

I tested Population One with ReliveVR, but didn't get to the opening credits, then I was only shown a dark background. The game didn't get stuck, it looks like it can't load something.

It works perfectly with Oculus Link. But would like to play wirelessly via ReliveVR :)

Thanks!

**Comment by GennadiyAMD** [comment]
@eywhat - could you try changing headset emulation to HTC Vive or Vive Pro and see if that takes you any further? There is a category of games that start using the Oculus native API directly, bypassing OpenVR, when they detect an Oculus headset. If it starts working after switching to HTC, then we would know that this is the case. If so, trying to run it under Revive might be helpful.

**Comment by eywhat** [comment]
After an update, the game now starts with ReliveVR. The controllers can be seen, but the buttons do not work.

**Comment by GennadiyAMD** [comment]
@eywhat - do controllers respond to movements? Have you tried switching emulation to HTC Vive as I suggested?

**Comment by eywhat** [comment]
ReliveVR now works completely with PopulationOne ; )
