### ISSUE TITLE
Why is this in "GPUOpen" when it's closed source?

### ISSUE THREAD

**Issue by nat42** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#84]
I thought GPUOpen was meant to be open source, this seems like a closed source offering, putting a compiled and packaged binary on Github does not make software open source?

It would be nice to be able to look at the source maybe consider trying to hack on it, perhaps to customise the 6DOF position emulation for 3DOF controllers with keyboard shortcuts for like arm extension or something (I dunno that's the point of open source perhaps someone else might thing of a clever hack to get another 3DOF data point by strapping a phone to the upper arm to enhance arm model)

**Comment by GennadiyAMD** [comment]
@nat42 
Hi Nat,

Not all content on GPUOpen is open source, even though the majority of it is. GPUOpen’s goal is to provide the user and the developer communities with ways to utilize the power of AMD GPUs to its full potential. This includes information about our GPUs, techniques of their efficient use, SDKs and code samples, documentation, open source software, as well as the closed source software that allows our users to use AMD GPUs in novel ways. ReLive VR allows our users to extract an additional value out AMD GPUs when combined with the third-party hardware and that is why we felt it was appropriate to host it under the GPUOpen umbrella. Having said that, AMD’s commitment to open-source software remains unchanged.
