### ISSUE TITLE
Star Wars Squadrons not recognising emulated headset

### ISSUE THREAD

**Issue by paranoidandy** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#87]
Tried every possible way to get into VR mode using ReLive VR. Nothing works. Tried starting inside SteamVR, from the Steam library launcher selecting SteamVR mode, from using the in game toggle, nothing. Also tried every type of emulated headset.

Most other SteamVR games at least start in VR, some have issues like incorrect controllers but in general ReLive VR works really well on my rx580.

Game plays fine using Virtual Desktop so there's nothing wrong with SteamVR or the game install. But I really want to see if I get a little more performance using ReLive VR. Thanks!

**Comment by GennadiyAMD** [comment]
@paranoidandy - try running it under [ReVive](https://github.com/LibreVR/Revive). If you do, please let us know if it helps. Thanks!

We've seen a number of games lately that attempt to go to native headset APIs, bypassing OpenVR after they detect the respective headset. In some cases you can start the game from Steam, then kill SteamVR, but the game keeps running as if nothing happened. 

From what I can tell, VD seems to emulate the Oculus API directly, substituting the Oculus runtime. In this case SteamVR itself thinks it's talking to the real Oculus device. Revive does something similar at a different level, making the game think it's talking to a real Rift S or CV1. That's why I hope it might help.

**Comment by paranoidandy** [comment]
@GennadiyAMD thanks for the suggestion. However since as far as I know only Oculus games appear in ReVive (that's what it's there for) and I have the Steam version of Squadrons, I'm not sure it's possible to do that? I've tried the Revive dashboard both inside and outside of SteamVR and it only lists installed Oculus games.

Perhaps the Oculus version of Squadrons would work this way, but I'm only able to try the SteamVR version direct from Steam. This is the version I was hoping to try using Radeon Relive VR.

Is it true that Virtual Desktop implements it's own runtime as a stand in for the Oculus one when running Oculus games. But I think it runs SteamVR games much like Radeon Relive VR does, and my copy of Squadrons works fine with Virtual Desktop run this way. Killing SteamVR does indeed kill the game in that case also.

**Comment by paranoidandy** [comment]
After updating Quest client to 1.0.25 and Radeon drivers to 20.12.1 Squadrons now works!

**Comment by GennadiyAMD** [comment]
@paranoidandy - great, thanks for letting us know. This has probably something to do with the driver update, not the client app. 

Btw, unrelated question: which fps are you getting in Steam Home?

**Comment by paranoidandy** [comment]
> Btw, unrelated question: which fps are you getting in Steam Home?

I mess around with the render and encoder resolutions and bitrate quite a bit so I'm not sure. I can do a test for you at some specified settings if you like?

**Comment by GennadiyAMD** [comment]
@paranoidandy - 72Hz is the right frame rate for the original Quest - that's what its display is running at. I was just trying to help the other folks who couldn't get to 90fps with Quest2 and was wondering what you were getting (somehow I thought you had Quest2 as well, although now, after re-reading the thread, I realize that I made an incorrect assumption). But at any rate, all problems have been resolved now, thanks for your help and responses. 

Btw, if you installed today's update from SideQuest, you might want to reinstall it again - there was a problem there that I just rectified, it was still loading 1.0.23. But if you got the apk from Github directly, you should be fine, no need to worry.

I'm closing this ticket for now, if anything, please feel free to file a new one.
