### ISSUE TITLE
NO STREAMING TAB FOR MY AMD SOFTWARE

### ISSUE THREAD

**Issue by frankieboy2000** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#89]
So my amd adrenaline version 20.12.1 doesnt have the streamng tab in it.i am using a laptop(nitro 5,amd 3550h with vega 8,rx 560x discrete graphics card,I am aware that i am not the only one having this problem in mobile apus but my rx 560x supports amd relive and shouldnt it be showing?...I have no clue if this can fixed or i am open to every help i can get.thank you.......

**Comment by RyanCarrier** [comment]
Where are you looking for this tab? it's under settings then general, then UNDERNEATH streaming there is a VR section

**Comment by GennadiyAMD** [comment]
@frankieboy2000 - do you have the c:\Program Files\AMD\WVR folder on your PC?

**Comment by renzhezhu1234** [comment]
Radeon 20.12.1 settings not have oculus quest2. The new Radeon - Relive - vr really support oculus quest2?

**Comment by renzhezhu1234** [comment]
My quest2 can't work normally, he still step the "wifi" mark.
![{G@1A5 }Y__387(37~{N032](https://user-images.githubusercontent.com/64953471/105173159-9717c100-5b5b-11eb-8268-c9ba7239400e.png)

**Comment by renzhezhu1234** [comment]
![9AYCRO99A6JYGZSSWE UNMR](https://user-images.githubusercontent.com/64953471/105173231-b0b90880-5b5b-11eb-8871-9da668e3adfe.png)

Look this.

**Comment by GennadiyAMD** [comment]
@renzhezhu1234 - I assume you've started SteamVR on the PC - launching ReLive VR on the headset would not start SteamVR automatically. If you did - check your firewall settings - chances are your network type is set to Public and firewall is not open for public networks by default. Change it to private. Also make sure that the PC and the headset are on the same IP subnet - i.e. their IP addresses have the same parts where subnet masks have non-zero values (say, your network is 192.168.0.x with the mask 255.255.255.0 - in this case the IP address of the PC and the headset should both start with 192.168.0 and the last number would be different). We've seen routers that assign different subnets to wired and wireless networks - this can also be the case with mesh routers.

I'd also suggest you read [this](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Network-Setup) and [this](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Troubleshooting) sections of our Wiki - there's plenty of recommendations on setting up the network there.

As for the headset emulation - select Oculus Rift S - it has the same controllers as Quest/Quest2.
