### ISSUE TITLE
Random artifacting and stutter

### ISSUE THREAD

**Issue by realistic40** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#9]
I'm experiencing random artifacting and stutter for a few seconds every 10-20 minutes. Issue occurs on all games and in Steam Home. Runs perfectly outside of that. I have Adrenaline 19.7.2 installed with a RX 590. I've tried bitrate set to high and medium and experience the issue both ways. I'm within line of site of my router connected at max speed for the Quest and my desktop is wired into the router.

**Comment by GennadiyAMD** [comment]
@realistic40 - you would see artifacts you're describing when some packets are occasionally lost or significantly delayed during transmission over the network. This might happen for many reasons - for example, interference on the network, the router or the headset performing some memory management tasks like garbage collection, some other task on the PC (like an antivirus or Windows Update) causing high CPU usage and so on. Not much can be done about this.

**Comment by realistic40** [comment]
Thank you for the response, are there any debugging logs that you could point me to that may assist with locating the issue? I don't experience the same issue when using alvr or vridge which is why I opened this issue.

**Comment by GennadiyAMD** [comment]
@realistic40 - our default "medium" bitrate is 50Mbps. As far as I know, the defaults for ALVR and Vridge are lower than this. You can try reducing the bitrate by modifying the "VideoBitrate" parameter in the "Display" section of the settings.json file - see if 30000000 (30Mbps) would make a difference.

**Comment by realistic40** [comment]
I was going to test this, as well as updating to the new code, but it appears the Quest firmware update has caused the controllers to stop being recognized. Looks to be a known issue for sideloaded apps.

**Comment by realistic40** [comment]
The new release works great but I'm still experiencing the random stuttering/artifacting with 30Mbps as well. Any other suggestions related to settings/driver or should I start looking at my network?

**Comment by GennadiyAMD** [comment]
@realistic40 - we have a log file called AMDWirelessVR.log placed in the Steam's log folder (Program Files (x86)\Steam\logs). Please attach to the issue.

Would also be interesting to monitor CPU, GPU and network activity in Windows Task Manager/Performance tab. See if you notice any spikes in activity around the time when you see artifacts. You could also use Wattman (Radeon Settings->Gaming->Global Settings->Global Wattman) to monitor GPU temperature and fan speeds - look for spikes around the time of artifacts. 

You could also try switching to steaming over TCP instead of UDP (change the value of Headset.Network to "TCP" in settings.json and restart SteamVR to take effect), see if this works better for you. You might experience higher latency that accumulates over time with TCP though.

What is your router model?

**Comment by realistic40** [comment]
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/3444619/AMDWirelessVR.log)

I'll monitor CPU/GPU/Network and see if I see a correlation, as well as try the TCP instead of UDP change and report back. Router model is NETGEAR Nighthawk AC1750 Smart Dual Band WiFi Router (R6700)

**Comment by realistic40** [comment]
There does look to be a surge of network activity that goes over the 100Mbps mark that Windows provides in the resource monitor when the issue occurs. I'm going to try TCP and see if that makes a difference.

**Comment by realistic40** [comment]
After changing it to TCP I still get the occasional 1-2 seconds of stutter, but no degradation of picture or sound which makes it a lot easier to handle. I'll keep looking to see what is randomly using my network and causing such a big spike in usage. Let me know if you see anything in the AMDWirelessVR logs

**Comment by GennadiyAMD** [comment]
@realistic40 - Which title did you capture this log with? Did you create a custom game/wattman profile in Radeon Settings for this game or change the global profile? Are all GPU fans spinning?

**Comment by realistic40** [comment]
@GennadiyAMD I captured the log playing Serious Sam. I did not create a custom game/wattman profile or change the global profile, and all GPU fans are spinning. I did not see any CPU/GPU spikes when the issue occurs, just the network spikes but I haven't been able to determine what is causing them because I don't see them when I'm not streaming VR. I did update my network driver but I haven't had a chance to test and see if the issue is still there. I'll test later today and report back.

**Comment by realistic40** [comment]
@GennadiyAMD After the driver update the issue is much smaller and less frequent, I switched back to UDP due to the increase in latency and when I do get the stutter (once every half hour or less), it only lasts a couple of seconds without visual picture degradation which is the best of both worlds. I'm going to go ahead and close this out as I think it's been as optimized as it can be without me finding something taking up network bandwidth on my machine. Thanks for the help, it's much appreciated!
