### ISSUE TITLE
BoneWorks HandOffset

### ISSUE THREAD

**Issue by Loch-dev** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#93]
Here is a video of the issue. Seen multiple forum posts for this. Devs of the game refuse to fix this as it's not an issue with the game and more of an issue with the third party software.

As you can see in the video the hands are completely off. Virtual Desktop has already patched this, not sure how.

https://youtu.be/kFXntiws2lw

Hope this can be resolved. I really loved playing it with the Link cable, but I'm not able to anymore because I moved, so I have to play wirelessly.

Tried fixing with OVR, but it's not possible.

**Comment by GennadiyAMD** [comment]
@Loch-dev - we view it as a game issue as other games work fine. Our ability to debug this without game dev's cooperation is very limited. It seems that the game misinterprets the Oculus controller coordinates when running over the OpenVR interface. ReLive VR doesn't adjust the controller coordinates in any way, whatever it gets from the headset is passed to the game. As you can see in your own video, controllers' position is correct in SteamVR Home and other games.

I can only guess what the game is doing, but we've seen games that would attempt to use the Oculus API directly even under Steam. In case of ReLive VR this API is simply not present as there isn't a real device connected to the PC that the Oculus runtime can recognize. Some games would simply fail (there was an issue with Superhot at some point, for example), some would fall back to using the OpenVR API. But if they treat hand coordinates differently with the two APIs, you would get this misalignment.

As far as I know, VD actually emulates the Oculus API, so the game thinks that it is connected to a real Oculus and behaves differently. There are reasons why we can't do the same, and unfortunately you can't adjust controller positions per title as SteamVR isn't aware of which game is running.

Not the answer you were hoping for, I know, but that's what it is, sorry :(.

**Comment by Loch-dev** [comment]
Thanks @GennadiyAMD for the reply. At least I can understand this, Boneworks Devs basically told me to piss off and GTFO on the steam community hub because I can't use the 'official' oculus link cable. If only they knew or cared, ay?

Thanks for ReLiveVR though. It's absolutely perfect for everything else.

**Comment by GennadiyAMD** [comment]
@Loch-dev - thanks! 👍
